// Generated by AI. Requires qualified professional review.
import { NextResponse } from "next/server";
// import { logAuditEvent } from "@/server/services/audit-log";

const mockDepartments = [
  {
    id: "DEPT-001",
    name: "Quality Assurance",
    code: "QA",
    head: "Dr. Sarah Chen",
    memberCount: 8,
    isActive: true,
  },
  {
    id: "DEPT-002",
    name: "Regulatory Affairs",
    code: "RA",
    head: "Aisha Patel",
    memberCount: 5,
    isActive: true,
  },
  {
    id: "DEPT-003",
    name: "Engineering",
    code: "ENG",
    head: "David Thornton",
    memberCount: 12,
    isActive: true,
  },
  {
    id: "DEPT-004",
    name: "Manufacturing",
    code: "MFG",
    head: "Michael Okafor",
    memberCount: 20,
    isActive: true,
  },
  {
    id: "DEPT-005",
    name: "Clinical Affairs",
    code: "CLA",
    head: "Robert Müller",
    memberCount: 4,
    isActive: true,
  },
  {
    id: "DEPT-006",
    name: "Supply Chain",
    code: "SCM",
    head: "Pending Assignment",
    memberCount: 0,
    isActive: false,
  },
];

export async function GET() {
  return NextResponse.json({
    departments: mockDepartments,
    total: mockDepartments.length,
  });
}

export async function POST(request: Request) {
  const body = await request.json();
  // await logAuditEvent({ action: "DEPARTMENT_CREATED", details: body });
  void body;
  return NextResponse.json({ success: true }, { status: 201 });
}

export async function PATCH(request: Request) {
  const body = await request.json();
  // await logAuditEvent({ action: "DEPARTMENT_UPDATED", details: body });
  void body;
  return NextResponse.json({ success: true });
}

export async function DELETE(request: Request) {
  const body = await request.json();
  // await logAuditEvent({ action: "DEPARTMENT_DELETED", details: body });
  void body;
  return NextResponse.json({ success: true });
}
