// Generated by AI. Requires qualified professional review.
import { NextResponse } from "next/server";

const mockLeaveRequests = [
  { id: "lr-001", employeeId: "emp-001", name: "Alice Johnson", type: "vacation", startDate: "2026-05-01", endDate: "2026-05-05", hours: 40, status: "pending", submittedAt: "2026-03-28" },
  { id: "lr-002", employeeId: "emp-003", name: "Carol Davis", type: "personal", startDate: "2026-04-15", endDate: "2026-04-15", hours: 8, status: "pending", submittedAt: "2026-03-30" },
  { id: "lr-003", employeeId: "emp-002", name: "Bob Smith", type: "vacation", startDate: "2026-04-20", endDate: "2026-04-24", hours: 40, status: "approved", approvedBy: "mgr-001", approvedAt: "2026-03-15" },
  { id: "lr-004", employeeId: "emp-005", name: "Eva Martinez", type: "sick", startDate: "2026-03-25", endDate: "2026-03-26", hours: 16, status: "approved", approvedBy: "mgr-002", approvedAt: "2026-03-25" },
  { id: "lr-005", employeeId: "emp-007", name: "Grace Chen", type: "vacation", startDate: "2026-06-01", endDate: "2026-06-12", hours: 80, status: "approved", approvedBy: "mgr-003", approvedAt: "2026-03-20" },
  { id: "lr-006", employeeId: "emp-004", name: "Dan Wilson", type: "fmla", startDate: "2026-04-01", endDate: "2026-06-30", hours: 480, status: "approved", approvedBy: "hr-001", approvedAt: "2026-03-15" },
];

export async function GET() {
  const isHrAdmin = true; // mock hr_admin flag

  const data = mockLeaveRequests.map((request) => {
    if (request.type === "fmla" && isHrAdmin) {
      return {
        ...request,
        fmlaDetails: {
          reason: "serious_health_condition",
          certificationReceived: true,
          certificationDate: "2026-03-10",
          expectedReturnDate: "2026-07-01",
        },
      };
    }
    return request;
  });

  return NextResponse.json({ data, total: data.length });
}

export async function POST() {
  return NextResponse.json({ success: true, message: "Leave request submitted" });
}
