// Generated by AI. Requires qualified professional review.
import { NextResponse } from "next/server";

export async function PATCH() {
  return NextResponse.json({ success: true, message: "Leave request updated" });
}

export async function DELETE() {
  return NextResponse.json({ success: true, message: "Leave request cancelled" });
}
