// Generated by AI. Requires qualified professional review.
import { NextResponse } from "next/server";

const mockOverdueTraining = [
  { id: "tr-004", employeeId: "emp-004", name: "Dan Wilson", course: "CAPA Procedures", status: "overdue", assignedDate: "2025-11-01", dueDate: "2026-01-31", daysOverdue: 61 },
  { id: "tr-010", employeeId: "emp-003", name: "Carol Davis", course: "Supplier Quality Management", status: "overdue", assignedDate: "2025-12-01", dueDate: "2026-02-28", daysOverdue: 33 },
];

export async function GET() {
  return NextResponse.json({ data: mockOverdueTraining, total: mockOverdueTraining.length });
}
