// Generated by AI. Requires qualified professional review.
import { NextResponse } from "next/server";
// import { logAuditEvent } from "@/server/services/audit-log";

const mockSignatures = [
  {
    id: "SIG-001",
    userId: "USR-001",
    userName: "Dr. Sarah Chen",
    documentId: "DOC-2045",
    documentTitle: "Design Verification Protocol - Revision C",
    action: "approved",
    meaning: "I have reviewed and approve this document",
    method: "password",
    ipAddress: "10.0.1.42",
    timestamp: "2026-04-01T14:30:00Z",
  },
  {
    id: "SIG-002",
    userId: "USR-002",
    userName: "James Rodriguez",
    documentId: "DOC-2044",
    documentTitle: "510(k) Submission Package - Rev B",
    action: "approved",
    meaning: "I have reviewed and approve this document",
    method: "password",
    ipAddress: "10.0.1.55",
    timestamp: "2026-03-31T16:00:00Z",
  },
  {
    id: "SIG-003",
    userId: "USR-005",
    userName: "Lisa Park",
    documentId: "CAPA-0089",
    documentTitle: "CAPA Effectiveness Check - Soldering Defect",
    action: "reviewed",
    meaning: "I have reviewed this record",
    method: "password",
    ipAddress: "10.0.1.30",
    timestamp: "2026-03-30T11:15:00Z",
  },
  {
    id: "SIG-004",
    userId: "USR-003",
    userName: "Emily Watson",
    documentId: "RA-0312",
    documentTitle: "Risk Analysis - Battery Module v2",
    action: "authored",
    meaning: "I am the author of this document",
    method: "password",
    ipAddress: "10.0.1.18",
    timestamp: "2026-03-29T09:45:00Z",
  },
  {
    id: "SIG-005",
    userId: "USR-004",
    userName: "Michael Okafor",
    documentId: "NCR-0456",
    documentTitle: "Nonconformance Report - Incoming Inspection Lot 7742",
    action: "approved",
    meaning: "I have reviewed and approve this document",
    method: "password",
    ipAddress: "10.0.2.10",
    timestamp: "2026-03-28T15:20:00Z",
  },
];

export async function GET() {
  return NextResponse.json({
    signatures: mockSignatures,
    total: mockSignatures.length,
  });
}

export async function POST(request: Request) {
  const body = await request.json();
  // await logAuditEvent({ action: "SIGNATURE_RECORDED", details: body });
  void body;
  return NextResponse.json(
    { success: true, message: "Signature recorded" },
    { status: 201 }
  );
}
