// Generated by AI. Requires qualified professional review.
import { NextResponse } from "next/server";

const mockCompensation = [
  { id: "comp-001", employeeId: "emp-001", name: "Alice Johnson", amount: 125000, type: "salary", payGrade: "L5", bonusEligible: true, effectiveStart: "2026-01-01" },
  { id: "comp-002", employeeId: "emp-002", name: "Bob Smith", amount: 98000, type: "salary", payGrade: "L4", bonusEligible: true, effectiveStart: "2025-07-01" },
  { id: "comp-003", employeeId: "emp-003", name: "Carol Davis", amount: 145000, type: "salary", payGrade: "L6", bonusEligible: true, effectiveStart: "2026-01-01" },
  { id: "comp-004", employeeId: "emp-004", name: "Dan Wilson", amount: 82000, type: "salary", payGrade: "L3", bonusEligible: false, effectiveStart: "2025-03-15" },
  { id: "comp-005", employeeId: "emp-005", name: "Eva Martinez", amount: 110000, type: "salary", payGrade: "L5", bonusEligible: true, effectiveStart: "2026-01-01" },
  { id: "comp-006", employeeId: "emp-006", name: "Frank Lee", amount: 72000, type: "hourly", payGrade: "L2", bonusEligible: false, effectiveStart: "2025-09-01" },
  { id: "comp-007", employeeId: "emp-007", name: "Grace Chen", amount: 135000, type: "salary", payGrade: "L6", bonusEligible: true, effectiveStart: "2025-06-01" },
  { id: "comp-008", employeeId: "emp-008", name: "Hank Brown", amount: 91000, type: "salary", payGrade: "L4", bonusEligible: true, effectiveStart: "2026-02-01" },
];

export async function GET() {
  return NextResponse.json({ data: mockCompensation, total: mockCompensation.length });
}

export async function POST() {
  return NextResponse.json({ success: true, message: "Compensation record created" });
}
