// Generated by AI. Requires qualified professional review.
import { NextResponse } from "next/server";
// import { logAuditEvent } from "@/server/services/audit-log";

const mockUser = {
  id: "USR-001",
  name: "Dr. Sarah Chen",
  email: "sarah.chen@meddevice.com",
  department: "Quality Assurance",
  role: "Quality Manager",
  status: "active",
  lastLogin: "2026-04-01T14:32:00Z",
  createdAt: "2024-06-15T09:00:00Z",
  updatedAt: "2026-03-20T11:00:00Z",
  phone: "+1-555-0142",
  title: "Senior Quality Manager",
  trainingStatus: "current",
  signatureOnFile: true,
};

export async function GET(
  _request: Request,
  { params }: { params: { id: string } }
) {
  void params;
  return NextResponse.json({ user: mockUser });
}

export async function PATCH(
  request: Request,
  { params }: { params: { id: string } }
) {
  const body = await request.json();
  // await logAuditEvent({ action: "USER_UPDATED", userId: params.id, details: body });
  void body;
  void params;
  return NextResponse.json({ success: true, message: "User updated" });
}
