// Generated by AI. Requires qualified professional review.
"use client";

import { useState } from "react";
import { cn } from "@/lib/utils";
import {
  ShieldCheck,
  Users,
  KeyRound,
  Building2,
  ArrowRightLeft,
  ScrollText,
  UserCog,
  Calendar,
  GraduationCap,
  DollarSign,
  TrendingUp,
  Clock,
  AlertTriangle,
} from "lucide-react";

import { UsersTab } from "./components/users-tab";
import { RolesTab } from "./components/roles-tab";
import { DepartmentsTab } from "./components/departments-tab";
import { DelegationsTab } from "./components/delegations-tab";
import { AuditLogsTab } from "./components/audit-logs-tab";
import { EmployeeProfilesTab } from "./components/employee-profiles-tab";
import { LeaveTab } from "./components/leave-tab";
import { TrainingCertsTab } from "./components/training-certs-tab";
import { CompensationTab } from "./components/compensation-tab";
import { PerformanceTab } from "./components/performance-tab";

const summaryCards = [
  { label: "Total Users", value: 8, icon: Users, color: "text-blue-600", bg: "bg-blue-50" },
  { label: "Active Roles", value: 9, icon: KeyRound, color: "text-purple-600", bg: "bg-purple-50" },
  { label: "Pending Leave", value: 2, icon: Clock, color: "text-amber-600", bg: "bg-amber-50" },
  { label: "Overdue Training", value: 2, icon: AlertTriangle, color: "text-red-600", bg: "bg-red-50" },
];

const adminTabs = [
  { id: "users", label: "Users", icon: Users },
  { id: "roles", label: "Roles & Permissions", icon: KeyRound },
  { id: "departments", label: "Departments", icon: Building2 },
  { id: "delegations", label: "Delegations", icon: ArrowRightLeft },
  { id: "audit-logs", label: "Audit Logs", icon: ScrollText },
];

const hrTabs = [
  { id: "employee-profiles", label: "Employee Profiles", icon: UserCog },
  { id: "leave", label: "Leave / PTO", icon: Calendar },
  { id: "training-certs", label: "Training & Certs", icon: GraduationCap },
  { id: "compensation", label: "Compensation", icon: DollarSign },
  { id: "performance", label: "Performance", icon: TrendingUp },
];

export default function AdminPage() {
  const [activeTab, setActiveTab] = useState("users");

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <div className="p-2 bg-slate-100 rounded-lg">
          <ShieldCheck className="h-6 w-6 text-slate-600" />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Admin &amp; HR</h1>
          <p className="text-sm text-gray-500">User administration, roles, permissions, HR management, and compliance controls</p>
        </div>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {summaryCards.map((c) => (
          <div key={c.label} className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
            <div className={cn("p-2 rounded-lg w-fit", c.bg)}>
              <c.icon className={cn("h-5 w-5", c.color)} />
            </div>
            <p className="mt-3 text-2xl font-bold text-gray-900">{c.value}</p>
            <p className="text-sm text-gray-500">{c.label}</p>
          </div>
        ))}
      </div>

      {/* Tab Navigation with Admin / HR separator */}
      <div className="border-b border-gray-200">
        <nav className="flex gap-1 -mb-px overflow-x-auto">
          {/* Admin Tabs */}
          {adminTabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={cn(
                "flex items-center gap-2 px-4 py-2.5 text-sm font-medium border-b-2 whitespace-nowrap transition-colors",
                activeTab === tab.id
                  ? "border-blue-600 text-blue-600"
                  : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300"
              )}
            >
              <tab.icon className="h-4 w-4" />
              {tab.label}
            </button>
          ))}

          {/* Separator */}
          <div className="flex items-center px-2">
            <div className="h-6 w-px bg-gray-300" />
            <span className="ml-2 text-[10px] font-semibold text-gray-400 uppercase tracking-wider">HR</span>
          </div>

          {/* HR Tabs */}
          {hrTabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={cn(
                "flex items-center gap-2 px-4 py-2.5 text-sm font-medium border-b-2 whitespace-nowrap transition-colors",
                activeTab === tab.id
                  ? "border-emerald-600 text-emerald-600"
                  : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300"
              )}
            >
              <tab.icon className="h-4 w-4" />
              {tab.label}
            </button>
          ))}
        </nav>
      </div>

      {/* Active Tab Content */}
      {activeTab === "users" && <UsersTab />}
      {activeTab === "roles" && <RolesTab />}
      {activeTab === "departments" && <DepartmentsTab />}
      {activeTab === "delegations" && <DelegationsTab />}
      {activeTab === "audit-logs" && <AuditLogsTab />}
      {activeTab === "employee-profiles" && <EmployeeProfilesTab />}
      {activeTab === "leave" && <LeaveTab />}
      {activeTab === "training-certs" && <TrainingCertsTab />}
      {activeTab === "compensation" && <CompensationTab />}
      {activeTab === "performance" && <PerformanceTab />}
    </div>
  );
}
