// Generated by AI. Requires qualified professional review.
"use client";

import { useState } from "react";
import { cn, getStatusColor } from "@/lib/utils";
import {
  ShieldCheck,
  Users,
  KeyRound,
  Building2,
  ArrowRightLeft,
  ScrollText,
} from "lucide-react";

import { UsersTab } from "./components/users-tab";
import { RolesTab } from "./components/roles-tab";
import { DepartmentsTab } from "./components/departments-tab";
import { DelegationsTab } from "./components/delegations-tab";
import { AuditLogsTab } from "./components/audit-logs-tab";

const summaryCards = [
  { label: "Total Users", value: 8, icon: Users, color: "text-blue-600", bg: "bg-blue-50" },
  { label: "Active Roles", value: 9, icon: KeyRound, color: "text-purple-600", bg: "bg-purple-50" },
  { label: "Departments", value: 6, icon: Building2, color: "text-teal-600", bg: "bg-teal-50" },
  { label: "Delegations", value: 1, icon: ArrowRightLeft, color: "text-orange-600", bg: "bg-orange-50" },
];

const tabs = [
  { id: "users", label: "Users", icon: Users },
  { id: "roles", label: "Roles & Permissions", icon: KeyRound },
  { id: "departments", label: "Departments", icon: Building2 },
  { id: "delegations", label: "Delegations", icon: ArrowRightLeft },
  { id: "audit-logs", label: "Audit Logs", icon: ScrollText },
];

export default function AdminPage() {
  const [activeTab, setActiveTab] = useState("users");

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <div className="p-2 bg-slate-100 rounded-lg">
          <ShieldCheck className="h-6 w-6 text-slate-600" />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Administration</h1>
          <p className="text-sm text-gray-500">User administration, roles, permissions, and compliance controls</p>
        </div>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {summaryCards.map((c) => (
          <div key={c.label} className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
            <div className={cn("p-2 rounded-lg w-fit", c.bg)}>
              <c.icon className={cn("h-5 w-5", c.color)} />
            </div>
            <p className="mt-3 text-2xl font-bold text-gray-900">{c.value}</p>
            <p className="text-sm text-gray-500">{c.label}</p>
          </div>
        ))}
      </div>

      {/* Tab Navigation */}
      <div className="border-b border-gray-200">
        <nav className="flex gap-1 -mb-px overflow-x-auto">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={cn(
                "flex items-center gap-2 px-4 py-2.5 text-sm font-medium border-b-2 whitespace-nowrap transition-colors",
                activeTab === tab.id
                  ? "border-blue-600 text-blue-600"
                  : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300"
              )}
            >
              <tab.icon className="h-4 w-4" />
              {tab.label}
            </button>
          ))}
        </nav>
      </div>

      {/* Active Tab Content */}
      {activeTab === "users" && <UsersTab />}
      {activeTab === "roles" && <RolesTab />}
      {activeTab === "departments" && <DepartmentsTab />}
      {activeTab === "delegations" && <DelegationsTab />}
      {activeTab === "audit-logs" && <AuditLogsTab />}
    </div>
  );
}
