// Generated by AI. Requires qualified professional review.
import { NextResponse } from "next/server";

const mockExpiringCertifications = [
  { id: "tr-001", employeeId: "emp-001", name: "Alice Johnson", course: "GMP Fundamentals", expiresAt: "2026-12-20", daysUntilExpiry: 89 },
  { id: "tr-003", employeeId: "emp-003", name: "Carol Davis", course: "Risk Management (ISO 14971)", expiresAt: "2026-11-01", daysUntilExpiry: 40 },
  { id: "tr-007", employeeId: "emp-007", name: "Grace Chen", course: "Design Controls", expiresAt: "2026-10-15", daysUntilExpiry: 23 },
  { id: "tr-005", employeeId: "emp-005", name: "Eva Martinez", course: "Document Control", expiresAt: "2027-02-05", daysUntilExpiry: 78 },
];

export async function GET() {
  return NextResponse.json({ data: mockExpiringCertifications, total: mockExpiringCertifications.length });
}
