// Generated by AI. Requires qualified professional review.
"use client";

import { cn, getStatusColor } from "@/lib/utils";
import { ScrollText, Filter, ShieldAlert } from "lucide-react";

const auditLogs = [
  { id: 1, timestamp: "Apr 2, 2026 09:15 AM", user: "Tyler Ford", action: "Login", entityType: "Session", entityId: "SES-20260402-001", module: "Admin", changes: "Successful authentication" },
  { id: 2, timestamp: "Apr 1, 2026 02:30 PM", user: "Tyler Ford", action: "Role Assignment", entityType: "User", entityId: "USR-005", module: "Admin", changes: "Assigned QA Approver role to James Wilson" },
  { id: 3, timestamp: "Apr 1, 2026 10:45 AM", user: "Dr. Sarah Chen", action: "Delegation Created", entityType: "Delegation", entityId: "DEL-001", module: "Admin", changes: "Delegated Quality module to James Wilson (Apr 5–12)" },
  { id: 4, timestamp: "Mar 31, 2026 04:20 PM", user: "Tyler Ford", action: "Permission Update", entityType: "Role", entityId: "ROL-009", module: "Admin", changes: "Label Reviewer: added approve on Labeling" },
  { id: 5, timestamp: "Mar 30, 2026 11:00 AM", user: "Amy Rodriguez", action: "Document Approved", entityType: "Document", entityId: "DOC-2026-088", module: "Documents", changes: "SOP-QA-012 Rev 3 approved and set to effective" },
  { id: 6, timestamp: "Mar 28, 2026 10:20 AM", user: "Tyler Ford", action: "Department Update", entityType: "Department", entityId: "DEPT-006", module: "Admin", changes: "Set Robert Kim as head of Clinical" },
  { id: 7, timestamp: "Mar 28, 2026 10:15 AM", user: "Tyler Ford", action: "User Created", entityType: "User", entityId: "USR-008", module: "Admin", changes: "Created user Robert Kim (Clinical, Department Head)" },
  { id: 8, timestamp: "Mar 25, 2026 04:45 PM", user: "Tyler Ford", action: "Role Modified", entityType: "Role", entityId: "ROL-008", module: "Admin", changes: "QA Auditor: updated edit permissions for Audit Trail" },
  { id: 9, timestamp: "Mar 24, 2026 09:30 AM", user: "Dr. Sarah Chen", action: "CAPA Created", entityType: "CAPA", entityId: "CAPA-2026-041", module: "Quality", changes: "Opened CAPA for sterility assurance failure" },
  { id: 10, timestamp: "Mar 22, 2026 02:15 PM", user: "Tyler Ford", action: "User Deactivated", entityType: "User", entityId: "USR-010", module: "Admin", changes: "Deactivated user David Lee (departed employee)" },
  { id: 11, timestamp: "Mar 20, 2026 11:30 AM", user: "Lisa Park", action: "Submission Created", entityType: "Submission", entityId: "SUB-2026-015", module: "Regulatory", changes: "510(k) submission initiated for CardioSense Pro" },
  { id: 12, timestamp: "Mar 18, 2026 03:00 PM", user: "Mark Thompson", action: "Design Review", entityType: "Design Control", entityId: "DC-2026-009", module: "Design", changes: "Design review completed for OrthoFlex v2.1" },
  { id: 13, timestamp: "Mar 15, 2026 10:00 AM", user: "Tyler Ford", action: "Role Created", entityType: "Role", entityId: "ROL-009", module: "Admin", changes: "Created custom role Label Reviewer" },
  { id: 14, timestamp: "Mar 14, 2026 08:50 AM", user: "Lisa Park", action: "Delegation Expired", entityType: "Delegation", entityId: "DEL-002", module: "Admin", changes: "Regulatory delegation to Dr. Sarah Chen expired" },
  { id: 15, timestamp: "Mar 12, 2026 01:45 PM", user: "James Wilson", action: "Audit Completed", entityType: "Audit", entityId: "AUD-2026-003", module: "Quality", changes: "Internal audit of sterilization department completed" },
  { id: 16, timestamp: "Mar 10, 2026 09:00 AM", user: "Lisa Park", action: "Delegation Created", entityType: "Delegation", entityId: "DEL-002", module: "Admin", changes: "Delegated Regulatory to Dr. Sarah Chen (Mar 10–14)" },
  { id: 17, timestamp: "Mar 8, 2026 04:30 PM", user: "Tyler Ford", action: "Role Created", entityType: "Role", entityId: "ROL-008", module: "Admin", changes: "Created custom role QA Auditor" },
  { id: 18, timestamp: "Mar 5, 2026 02:00 PM", user: "Tyler Ford", action: "Permission Update", entityType: "Role", entityId: "ROL-007", module: "Admin", changes: "Department Head: added approve on Supply Chain" },
  { id: 19, timestamp: "Mar 3, 2026 11:15 AM", user: "Dr. Sarah Chen", action: "Training Assigned", entityType: "Training", entityId: "TRN-2026-022", module: "Training", changes: "Assigned GMP refresher to Production team (6 users)" },
  { id: 20, timestamp: "Mar 1, 2026 09:00 AM", user: "Tyler Ford", action: "System Config", entityType: "Config", entityId: "CFG-001", module: "Admin", changes: "Updated password policy: min 12 chars, 90-day expiry" },
];

export function AuditLogsTab() {
  return (
    <div className="space-y-6">
      {/* Filters */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <div className="flex items-center gap-3 mb-4">
          <Filter className="h-4 w-4 text-gray-400" />
          <span className="text-sm font-medium text-gray-700">Filters</span>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          <select className="border border-gray-200 rounded-lg px-3 py-2 text-sm text-gray-600 focus:outline-none focus:ring-2 focus:ring-blue-500">
            <option>All Actions</option>
            <option>User Created</option>
            <option>Role Assignment</option>
            <option>Permission Update</option>
            <option>Delegation Created</option>
            <option>User Deactivated</option>
            <option>Login</option>
          </select>
          <select className="border border-gray-200 rounded-lg px-3 py-2 text-sm text-gray-600 focus:outline-none focus:ring-2 focus:ring-blue-500">
            <option>All Entity Types</option>
            <option>User</option>
            <option>Role</option>
            <option>Delegation</option>
            <option>Document</option>
            <option>CAPA</option>
            <option>Config</option>
          </select>
          <select className="border border-gray-200 rounded-lg px-3 py-2 text-sm text-gray-600 focus:outline-none focus:ring-2 focus:ring-blue-500">
            <option>All Users</option>
            <option>Tyler Ford</option>
            <option>Dr. Sarah Chen</option>
            <option>Amy Rodriguez</option>
            <option>Mark Thompson</option>
            <option>James Wilson</option>
            <option>Lisa Park</option>
          </select>
        </div>
      </div>

      {/* Audit Log Table */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <h2 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
          <ScrollText className="h-5 w-5 text-gray-400" /> Audit Log
        </h2>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-200 text-left text-gray-500">
                <th className="pb-3 font-medium whitespace-nowrap">Timestamp</th>
                <th className="pb-3 font-medium">User</th>
                <th className="pb-3 font-medium">Action</th>
                <th className="pb-3 font-medium whitespace-nowrap">Entity Type</th>
                <th className="pb-3 font-medium whitespace-nowrap">Entity ID</th>
                <th className="pb-3 font-medium">Module</th>
                <th className="pb-3 font-medium">Changes</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {auditLogs.map((log) => (
                <tr key={log.id} className="hover:bg-gray-50">
                  <td className="py-3 text-gray-500 whitespace-nowrap text-xs">{log.timestamp}</td>
                  <td className="py-3 font-medium text-gray-800 whitespace-nowrap">{log.user}</td>
                  <td className="py-3">
                    <span className={cn(
                      "text-xs px-2 py-0.5 rounded-full font-medium",
                      log.action.includes("Created") || log.action === "Login"
                        ? getStatusColor("active")
                        : log.action.includes("Deactivated") || log.action.includes("Expired")
                        ? getStatusColor("closed")
                        : log.action.includes("Update") || log.action.includes("Modified") || log.action.includes("Assignment")
                        ? getStatusColor("in_progress")
                        : getStatusColor("pending")
                    )}>
                      {log.action}
                    </span>
                  </td>
                  <td className="py-3 text-gray-600 whitespace-nowrap">{log.entityType}</td>
                  <td className="py-3 font-mono text-xs text-blue-600 whitespace-nowrap">{log.entityId}</td>
                  <td className="py-3 text-gray-600">{log.module}</td>
                  <td className="py-3 text-gray-500 text-xs max-w-xs truncate">{log.changes}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* 21 CFR Part 11 Notice */}
      <div className="bg-amber-50 rounded-xl border border-amber-200 p-5">
        <div className="flex items-start gap-3">
          <ShieldAlert className="h-5 w-5 text-amber-600 mt-0.5 flex-shrink-0" />
          <div>
            <h3 className="text-sm font-semibold text-amber-800">21 CFR Part 11 — Audit Trail Immutability</h3>
            <p className="text-sm text-amber-700 mt-1">
              All audit trail records are immutable and cannot be modified or deleted. Each entry is timestamped,
              attributed to an authenticated user, and cryptographically signed. This audit trail complies with
              FDA 21 CFR Part 11 requirements for electronic records and electronic signatures.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
