// Generated by AI. Requires qualified professional review.
"use client";

import { useState } from "react";
import { cn, getStatusColor } from "@/lib/utils";
import {
  DollarSign,
  Users,
  TrendingUp,
  BarChart3,
  Lock,
  ShieldAlert,
  Eye,
  EyeOff,
} from "lucide-react";

const compensationData = [
  { id: 1, name: "Tyler Ford", title: "Founder & CEO", type: "Salary", amount: "$185,000", payGrade: "L6", bonus: "Yes (15%)", effective: "Jan 2025" },
  { id: 2, name: "Dr. Sarah Chen", title: "Quality Director", type: "Salary", amount: "$155,000", payGrade: "L5", bonus: "Yes (12%)", effective: "Feb 2025" },
  { id: 3, name: "Amy Rodriguez", title: "Doc Control Specialist", type: "Salary", amount: "$72,000", payGrade: "L3", bonus: "No", effective: "Mar 2025" },
  { id: 4, name: "Mark Thompson", title: "Sr. Design Engineer", type: "Salary", amount: "$130,000", payGrade: "L5", bonus: "Yes (10%)", effective: "Mar 2025" },
  { id: 5, name: "James Wilson", title: "QA Lead", type: "Salary", amount: "$95,000", payGrade: "L4", bonus: "Yes (8%)", effective: "Apr 2025" },
  { id: 6, name: "Lisa Park", title: "Regulatory Affairs Mgr", type: "Salary", amount: "$120,000", payGrade: "L5", bonus: "Yes (10%)", effective: "May 2025" },
  { id: 7, name: "Cynthia Ramirez", title: "Production Associate", type: "Hourly", amount: "$28/hr", payGrade: "L2", bonus: "No", effective: "Jun 2025" },
  { id: 8, name: "Robert Kim", title: "Clinical Affairs Director", type: "Salary", amount: "$145,000", payGrade: "L5", bonus: "Yes (12%)", effective: "Jul 2025" },
];

const summaryCards = [
  { label: "Monthly Payroll", value: "$87,458", icon: DollarSign, color: "text-green-600", bg: "bg-green-50" },
  { label: "Avg Salary", value: "$121,375", icon: TrendingUp, color: "text-blue-600", bg: "bg-blue-50" },
  { label: "Headcount", value: "8", icon: Users, color: "text-purple-600", bg: "bg-purple-50" },
  { label: "Bonus Eligible", value: "6", icon: BarChart3, color: "text-amber-600", bg: "bg-amber-50" },
];

export function CompensationTab() {
  const [hrAdminView, setHrAdminView] = useState(true);

  return (
    <div className="space-y-6">
      {/* Access Toggle */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-blue-50 rounded-lg">
              <DollarSign className="h-5 w-5 text-blue-600" />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-gray-900">Compensation Management</h2>
              <p className="text-sm text-gray-500">Salary, hourly rates, and bonus information</p>
            </div>
          </div>
          <button
            onClick={() => setHrAdminView(!hrAdminView)}
            className={cn(
              "flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg transition-colors",
              hrAdminView
                ? "text-blue-700 bg-blue-50 hover:bg-blue-100"
                : "text-gray-700 bg-gray-50 hover:bg-gray-100"
            )}
          >
            {hrAdminView ? <Eye className="h-4 w-4" /> : <EyeOff className="h-4 w-4" />}
            {hrAdminView ? "HR Admin View" : "Standard View"}
          </button>
        </div>
      </div>

      {!hrAdminView ? (
        /* Restricted Access Card */
        <div className="bg-gray-50 border border-gray-200 rounded-xl p-10">
          <div className="flex flex-col items-center justify-center text-center space-y-4">
            <div className="p-4 bg-gray-100 rounded-full">
              <Lock className="h-8 w-8 text-gray-400" />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-gray-700 mb-1">Access Restricted</h3>
              <p className="text-sm text-gray-500 max-w-md">
                Compensation data is restricted to HR Administrators. Contact your HR department for access.
              </p>
            </div>
          </div>
        </div>
      ) : (
        <>
          {/* Summary Cards */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {summaryCards.map((card) => (
              <div key={card.label} className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
                <div className="flex items-center gap-3">
                  <div className={cn("p-2 rounded-lg", card.bg)}>
                    <card.icon className={cn("h-5 w-5", card.color)} />
                  </div>
                  <div>
                    <p className="text-sm text-gray-500">{card.label}</p>
                    <p className="text-2xl font-semibold text-gray-900">{card.value}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Compensation Table */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
            <h2 className="text-lg font-semibold text-gray-900 mb-4">Compensation Details</h2>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-gray-200 text-left text-gray-500">
                    <th className="pb-3 font-medium">Employee</th>
                    <th className="pb-3 font-medium">Title</th>
                    <th className="pb-3 font-medium">Type</th>
                    <th className="pb-3 font-medium">Amount</th>
                    <th className="pb-3 font-medium">Pay Grade</th>
                    <th className="pb-3 font-medium">Bonus</th>
                    <th className="pb-3 font-medium">Effective Date</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {compensationData.map((e) => (
                    <tr key={e.id} className="hover:bg-gray-50">
                      <td className="py-3 font-medium text-gray-800">{e.name}</td>
                      <td className="py-3 text-gray-600">{e.title}</td>
                      <td className="py-3">
                        <span
                          className={cn(
                            "text-xs px-2 py-0.5 rounded-full font-medium",
                            e.type === "Salary"
                              ? "bg-blue-100 text-blue-800"
                              : "bg-purple-100 text-purple-800"
                          )}
                        >
                          {e.type}
                        </span>
                      </td>
                      <td className="py-3 font-medium text-gray-800">{e.amount}</td>
                      <td className="py-3 text-gray-600">{e.payGrade}</td>
                      <td className="py-3">
                        <span
                          className={cn(
                            "text-xs px-2 py-0.5 rounded-full font-medium",
                            e.bonus.startsWith("Yes")
                              ? "bg-green-100 text-green-800"
                              : "bg-gray-100 text-gray-600"
                          )}
                        >
                          {e.bonus}
                        </span>
                      </td>
                      <td className="py-3 text-gray-500 text-xs whitespace-nowrap">{e.effective}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* SOX / Privacy Notice */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
            <div className="flex items-start gap-3">
              <ShieldAlert className="h-5 w-5 text-gray-400 mt-0.5 shrink-0" />
              <p className="text-xs text-gray-500">
                Compensation data is classified as confidential and restricted to authorized HR personnel only.
                Access is logged and auditable per SOX compliance requirements. Unauthorized disclosure may result
                in disciplinary action. All changes are tracked with electronic signatures per 21 CFR Part 11.
              </p>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
