// Generated by AI. Requires qualified professional review.
"use client";

import { cn, getStatusColor } from "@/lib/utils";
import { ArrowRightLeft, CheckCircle2, Clock } from "lucide-react";

const activeDelegations = [
  {
    id: 1,
    delegator: "Dr. Sarah Chen",
    delegate: "James Wilson",
    module: "Quality",
    startDate: "Apr 5, 2026",
    endDate: "Apr 12, 2026",
    reason: "Annual leave",
    status: "active",
    createdBy: "Dr. Sarah Chen",
    createdAt: "Apr 1, 2026",
  },
];

const delegationHistory = [
  {
    id: 2,
    delegator: "Lisa Park",
    delegate: "Dr. Sarah Chen",
    module: "Regulatory",
    startDate: "Mar 10, 2026",
    endDate: "Mar 14, 2026",
    reason: "Conference attendance",
    status: "completed",
    createdBy: "Lisa Park",
    createdAt: "Mar 8, 2026",
  },
  {
    id: 3,
    delegator: "Amy Rodriguez",
    delegate: "Mark Thompson",
    module: "Documents",
    startDate: "Feb 20, 2026",
    endDate: "Feb 25, 2026",
    reason: "Medical leave",
    status: "completed",
    createdBy: "Tyler Ford",
    createdAt: "Feb 19, 2026",
  },
  {
    id: 4,
    delegator: "Robert Kim",
    delegate: "Dr. Sarah Chen",
    module: "Clinical",
    startDate: "Jan 15, 2026",
    endDate: "Jan 22, 2026",
    reason: "Site visit — external clinical trial",
    status: "completed",
    createdBy: "Robert Kim",
    createdAt: "Jan 13, 2026",
  },
  {
    id: 5,
    delegator: "Mark Thompson",
    delegate: "James Wilson",
    module: "Design",
    startDate: "Dec 22, 2025",
    endDate: "Jan 2, 2026",
    reason: "Holiday break",
    status: "completed",
    createdBy: "Mark Thompson",
    createdAt: "Dec 20, 2025",
  },
];

function DelegationTable({ delegations, title, icon }: { delegations: typeof activeDelegations; title: string; icon: React.ReactNode }) {
  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
      <h2 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
        {icon} {title}
      </h2>
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-gray-200 text-left text-gray-500">
              <th className="pb-3 font-medium">Delegator</th>
              <th className="pb-3 font-medium">Delegate</th>
              <th className="pb-3 font-medium">Module</th>
              <th className="pb-3 font-medium">Date Range</th>
              <th className="pb-3 font-medium">Reason</th>
              <th className="pb-3 font-medium">Status</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {delegations.map((d) => (
              <tr key={d.id} className="hover:bg-gray-50">
                <td className="py-3 font-medium text-gray-800">{d.delegator}</td>
                <td className="py-3 text-gray-600">{d.delegate}</td>
                <td className="py-3 text-gray-600">{d.module}</td>
                <td className="py-3 text-gray-500 whitespace-nowrap text-xs">
                  {d.startDate} — {d.endDate}
                </td>
                <td className="py-3 text-gray-500">{d.reason}</td>
                <td className="py-3">
                  <span className={cn("text-xs px-2 py-0.5 rounded-full font-medium", getStatusColor(d.status))}>
                    {d.status}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export function DelegationsTab() {
  return (
    <div className="space-y-6">
      <DelegationTable
        delegations={activeDelegations}
        title="Active Delegations"
        icon={<Clock className="h-5 w-5 text-orange-500" />}
      />
      <DelegationTable
        delegations={delegationHistory}
        title="Delegation History"
        icon={<CheckCircle2 className="h-5 w-5 text-gray-400" />}
      />
    </div>
  );
}
