// Generated by AI. Requires qualified professional review.
"use client";

import { cn, getStatusColor } from "@/lib/utils";
import { Building2 } from "lucide-react";

const departments = [
  { id: 1, name: "Quality", code: "QA", head: "Dr. Sarah Chen", members: 3, status: "active" },
  { id: 2, name: "Regulatory", code: "REG", head: "Lisa Park", members: 2, status: "active" },
  { id: 3, name: "Design & Engineering", code: "ENG", head: "Mark Thompson", members: 4, status: "active" },
  { id: 4, name: "Production", code: "PROD", head: "Cynthia Ramirez", members: 6, status: "active" },
  { id: 5, name: "Document Control", code: "DOC", head: "Amy Rodriguez", members: 2, status: "active" },
  { id: 6, name: "Clinical", code: "CLIN", head: "Robert Kim", members: 3, status: "active" },
];

export function DepartmentsTab() {
  return (
    <div className="space-y-6">
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <h2 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
          <Building2 className="h-5 w-5 text-gray-400" /> Departments
        </h2>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-200 text-left text-gray-500">
                <th className="pb-3 font-medium">Name</th>
                <th className="pb-3 font-medium">Code</th>
                <th className="pb-3 font-medium">Head</th>
                <th className="pb-3 font-medium">Members</th>
                <th className="pb-3 font-medium">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {departments.map((d) => (
                <tr key={d.id} className="hover:bg-gray-50">
                  <td className="py-3 font-medium text-gray-800">{d.name}</td>
                  <td className="py-3 font-mono text-xs text-blue-600">{d.code}</td>
                  <td className="py-3 text-gray-600">{d.head}</td>
                  <td className="py-3 text-gray-600">{d.members}</td>
                  <td className="py-3">
                    <span className={cn("text-xs px-2 py-0.5 rounded-full font-medium", getStatusColor(d.status))}>
                      {d.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
