// Generated by AI. Requires qualified professional review.
"use client";

import { useState } from "react";
import { cn, getStatusColor } from "@/lib/utils";
import {
  Search,
  User,
  MapPin,
  Briefcase,
  Calendar,
  Building2,
  UserX,
  PauseCircle,
} from "lucide-react";

const employees = [
  { id: 1, name: "Tyler Ford", title: "Founder & CEO", department: "Management", type: "Full-time", hireDate: "Jan 15, 2025", location: "Austin, TX", manager: "—", status: "active", email: "tyler@meddev.com", phone: "(512) 555-0101", dob: "Mar 12, 1985", emergencyContact: "Jessica Ford — (512) 555-0102" },
  { id: 2, name: "Dr. Sarah Chen", title: "Quality Director", department: "Quality", type: "Full-time", hireDate: "Feb 1, 2025", location: "Austin, TX", manager: "Tyler Ford", status: "active", email: "sarah@meddev.com", phone: "(512) 555-0201", dob: "Jul 8, 1980", emergencyContact: "David Chen — (512) 555-0202" },
  { id: 3, name: "Amy Rodriguez", title: "Doc Control Specialist", department: "Document Control", type: "Full-time", hireDate: "Mar 10, 2025", location: "Austin, TX", manager: "Dr. Sarah Chen", status: "active", email: "amy@meddev.com", phone: "(512) 555-0301", dob: "Nov 22, 1992", emergencyContact: "Carlos Rodriguez — (512) 555-0302" },
  { id: 4, name: "Mark Thompson", title: "Sr. Design Engineer", department: "Design & Engineering", type: "Full-time", hireDate: "Mar 15, 2025", location: "Remote", manager: "Tyler Ford", status: "active", email: "mark@meddev.com", phone: "(415) 555-0401", dob: "Sep 3, 1988", emergencyContact: "Jane Thompson — (415) 555-0402" },
  { id: 5, name: "James Wilson", title: "QA Lead", department: "Quality", type: "Full-time", hireDate: "Apr 1, 2025", location: "Austin, TX", manager: "Dr. Sarah Chen", status: "active", email: "james@meddev.com", phone: "(512) 555-0501", dob: "May 17, 1990", emergencyContact: "Karen Wilson — (512) 555-0502" },
  { id: 6, name: "Lisa Park", title: "Regulatory Affairs Mgr", department: "Regulatory", type: "Full-time", hireDate: "May 1, 2025", location: "Boston, MA", manager: "Tyler Ford", status: "active", email: "lisa@meddev.com", phone: "(617) 555-0601", dob: "Feb 28, 1987", emergencyContact: "Tom Park — (617) 555-0602" },
  { id: 7, name: "Cynthia Ramirez", title: "Production Associate", department: "Production", type: "Part-time", hireDate: "Jun 15, 2025", location: "Austin, TX", manager: "Tyler Ford", status: "active", email: "cynthia@meddev.com", phone: "(512) 555-0701", dob: "Aug 10, 1995", emergencyContact: "Maria Ramirez — (512) 555-0702" },
  { id: 8, name: "Robert Kim", title: "Clinical Affairs Director", department: "Clinical", type: "Full-time", hireDate: "Jul 1, 2025", location: "San Diego, CA", manager: "Tyler Ford", status: "active", email: "robert@meddev.com", phone: "(858) 555-0801", dob: "Dec 5, 1983", emergencyContact: "Susan Kim — (858) 555-0802" },
];

export function EmployeeProfilesTab() {
  const [search, setSearch] = useState("");

  const filtered = employees.filter(
    (e) =>
      e.name.toLowerCase().includes(search.toLowerCase()) ||
      e.title.toLowerCase().includes(search.toLowerCase()) ||
      e.department.toLowerCase().includes(search.toLowerCase()) ||
      e.location.toLowerCase().includes(search.toLowerCase())
  );

  const tyler = employees[0];

  return (
    <div className="space-y-6">
      {/* Search */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
          <input
            type="text"
            placeholder="Search employees by name, title, department, or location..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-10 pr-4 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
        </div>
      </div>

      {/* Employee Table */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <h2 className="text-lg font-semibold text-gray-900 mb-4">Employee Directory</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-200 text-left text-gray-500">
                <th className="pb-3 font-medium">Name</th>
                <th className="pb-3 font-medium">Title</th>
                <th className="pb-3 font-medium">Department</th>
                <th className="pb-3 font-medium">Employment Type</th>
                <th className="pb-3 font-medium">Hire Date</th>
                <th className="pb-3 font-medium">Location</th>
                <th className="pb-3 font-medium">Manager</th>
                <th className="pb-3 font-medium">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {filtered.map((e) => (
                <tr key={e.id} className="hover:bg-gray-50">
                  <td className="py-3 font-medium text-gray-800">{e.name}</td>
                  <td className="py-3 text-gray-600">{e.title}</td>
                  <td className="py-3 text-gray-600">{e.department}</td>
                  <td className="py-3">
                    <span
                      className={cn(
                        "text-xs px-2 py-0.5 rounded-full font-medium",
                        e.type === "Full-time"
                          ? "bg-blue-100 text-blue-800"
                          : "bg-purple-100 text-purple-800"
                      )}
                    >
                      {e.type}
                    </span>
                  </td>
                  <td className="py-3 text-gray-500 whitespace-nowrap text-xs">{e.hireDate}</td>
                  <td className="py-3 text-gray-600 whitespace-nowrap">{e.location}</td>
                  <td className="py-3 text-gray-600">{e.manager}</td>
                  <td className="py-3">
                    <span className={cn("text-xs px-2 py-0.5 rounded-full font-medium", getStatusColor(e.status))}>
                      {e.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Detail Panel — Tyler Ford */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <div className="flex items-center gap-3 mb-5">
          <div className="p-2 bg-blue-50 rounded-lg">
            <User className="h-5 w-5 text-blue-600" />
          </div>
          <div>
            <h2 className="text-lg font-semibold text-gray-900">{tyler.name}</h2>
            <p className="text-sm text-gray-500">{tyler.title} &middot; {tyler.department}</p>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Personal Info */}
          <div>
            <h3 className="text-sm font-semibold text-gray-700 mb-3 flex items-center gap-2">
              <User className="h-4 w-4 text-gray-400" /> Personal Info
            </h3>
            <div className="space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-gray-500">Email</span>
                <span className="text-gray-800">{tyler.email}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-gray-500">Phone</span>
                <span className="text-gray-800">{tyler.phone}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-gray-500">Date of Birth</span>
                <span className="text-gray-800">{tyler.dob}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-gray-500">Emergency Contact</span>
                <span className="text-gray-800 text-right text-xs">{tyler.emergencyContact}</span>
              </div>
            </div>
          </div>

          {/* Employment */}
          <div>
            <h3 className="text-sm font-semibold text-gray-700 mb-3 flex items-center gap-2">
              <Briefcase className="h-4 w-4 text-gray-400" /> Employment
            </h3>
            <div className="space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-gray-500">Department</span>
                <span className="text-gray-800">{tyler.department}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-gray-500">Employment Type</span>
                <span className="text-gray-800">{tyler.type}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-gray-500">Hire Date</span>
                <span className="text-gray-800">{tyler.hireDate}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-gray-500">Location</span>
                <span className="text-gray-800 flex items-center gap-1">
                  <MapPin className="h-3 w-3" /> {tyler.location}
                </span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-gray-500">Manager</span>
                <span className="text-gray-800">{tyler.manager}</span>
              </div>
            </div>
          </div>

          {/* Quick Actions */}
          <div>
            <h3 className="text-sm font-semibold text-gray-700 mb-3 flex items-center gap-2">
              <Building2 className="h-4 w-4 text-gray-400" /> Quick Actions
            </h3>
            <div className="space-y-3">
              <button className="w-full flex items-center gap-2 px-4 py-2 text-sm font-medium text-red-700 bg-red-50 rounded-lg hover:bg-red-100 transition-colors">
                <UserX className="h-4 w-4" /> Terminate Employee
              </button>
              <button className="w-full flex items-center gap-2 px-4 py-2 text-sm font-medium text-amber-700 bg-amber-50 rounded-lg hover:bg-amber-100 transition-colors">
                <PauseCircle className="h-4 w-4" /> Suspend Employee
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
