// Generated by AI. Requires qualified professional review.
"use client";

import { useState } from "react";
import { cn, getStatusColor } from "@/lib/utils";
import {
  Calendar,
  Clock,
  Users,
  TrendingUp,
  ShieldAlert,
  CheckCircle,
  XCircle,
} from "lucide-react";

const leaveBalances = [
  { id: 1, name: "Tyler Ford", vacationUsed: 24, vacationTotal: 160, sickUsed: 0, sickTotal: 64, personalUsed: 8, personalTotal: 24 },
  { id: 2, name: "Dr. Sarah Chen", vacationUsed: 40, vacationTotal: 160, sickUsed: 8, sickTotal: 64, personalUsed: 0, personalTotal: 24 },
  { id: 3, name: "Amy Rodriguez", vacationUsed: 16, vacationTotal: 120, sickUsed: 8, sickTotal: 40, personalUsed: 8, personalTotal: 16 },
  { id: 4, name: "Mark Thompson", vacationUsed: 32, vacationTotal: 160, sickUsed: 16, sickTotal: 64, personalUsed: 8, personalTotal: 24 },
  { id: 5, name: "James Wilson", vacationUsed: 24, vacationTotal: 120, sickUsed: 8, sickTotal: 40, personalUsed: 0, personalTotal: 16 },
  { id: 6, name: "Lisa Park", vacationUsed: 48, vacationTotal: 160, sickUsed: 16, sickTotal: 64, personalUsed: 16, personalTotal: 24 },
  { id: 7, name: "Cynthia Ramirez", vacationUsed: 16, vacationTotal: 120, sickUsed: 0, sickTotal: 40, personalUsed: 0, personalTotal: 16 },
  { id: 8, name: "Robert Kim", vacationUsed: 8, vacationTotal: 160, sickUsed: 8, sickTotal: 64, personalUsed: 8, personalTotal: 24 },
];

const pendingRequests = [
  { id: 1, employee: "James Wilson", type: "Vacation", startDate: "Apr 14, 2026", endDate: "Apr 18, 2026", hours: 40, status: "pending" },
  { id: 2, employee: "Lisa Park", type: "Sick", startDate: "Apr 7, 2026", endDate: "Apr 7, 2026", hours: 8, status: "pending" },
];

const requestHistory = [
  { id: 3, employee: "Dr. Sarah Chen", type: "Vacation", startDate: "Mar 10, 2026", endDate: "Mar 14, 2026", hours: 40, status: "approved", approvedBy: "Tyler Ford" },
  { id: 4, employee: "Mark Thompson", type: "Personal", startDate: "Feb 28, 2026", endDate: "Feb 28, 2026", hours: 8, status: "approved", approvedBy: "Tyler Ford" },
  { id: 5, employee: "Amy Rodriguez", type: "Sick", startDate: "Feb 14, 2026", endDate: "Feb 14, 2026", hours: 8, status: "approved", approvedBy: "Dr. Sarah Chen" },
];

const summaryCards = [
  { label: "Total PTO Hours", value: "1,248", icon: Clock, color: "text-blue-600", bg: "bg-blue-50" },
  { label: "Pending Requests", value: "2", icon: Calendar, color: "text-amber-600", bg: "bg-amber-50" },
  { label: "Avg Utilization", value: "42%", icon: TrendingUp, color: "text-green-600", bg: "bg-green-50" },
  { label: "FMLA Active", value: "0", icon: Users, color: "text-gray-600", bg: "bg-gray-50" },
];

export function LeaveTab() {
  const [requests, setRequests] = useState(pendingRequests);

  return (
    <div className="space-y-6">
      {/* Summary Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {summaryCards.map((card) => (
          <div key={card.label} className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
            <div className="flex items-center gap-3">
              <div className={cn("p-2 rounded-lg", card.bg)}>
                <card.icon className={cn("h-5 w-5", card.color)} />
              </div>
              <div>
                <p className="text-sm text-gray-500">{card.label}</p>
                <p className="text-2xl font-semibold text-gray-900">{card.value}</p>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Leave Balances */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <h2 className="text-lg font-semibold text-gray-900 mb-4">Leave Balances</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-200 text-left text-gray-500">
                <th className="pb-3 font-medium">Employee</th>
                <th className="pb-3 font-medium">Vacation (used/total)</th>
                <th className="pb-3 font-medium">Sick (used/total)</th>
                <th className="pb-3 font-medium">Personal (used/total)</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {leaveBalances.map((e) => (
                <tr key={e.id} className="hover:bg-gray-50">
                  <td className="py-3 font-medium text-gray-800">{e.name}</td>
                  <td className="py-3 text-gray-600">
                    {e.vacationUsed} / {e.vacationTotal} hrs
                    <div className="mt-1 w-24 h-1.5 bg-gray-100 rounded-full">
                      <div
                        className="h-1.5 bg-blue-500 rounded-full"
                        style={{ width: `${(e.vacationUsed / e.vacationTotal) * 100}%` }}
                      />
                    </div>
                  </td>
                  <td className="py-3 text-gray-600">
                    {e.sickUsed} / {e.sickTotal} hrs
                    <div className="mt-1 w-24 h-1.5 bg-gray-100 rounded-full">
                      <div
                        className="h-1.5 bg-amber-500 rounded-full"
                        style={{ width: `${(e.sickUsed / e.sickTotal) * 100}%` }}
                      />
                    </div>
                  </td>
                  <td className="py-3 text-gray-600">
                    {e.personalUsed} / {e.personalTotal} hrs
                    <div className="mt-1 w-24 h-1.5 bg-gray-100 rounded-full">
                      <div
                        className="h-1.5 bg-green-500 rounded-full"
                        style={{ width: `${(e.personalUsed / e.personalTotal) * 100}%` }}
                      />
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Pending Requests */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <h2 className="text-lg font-semibold text-gray-900 mb-4">Pending Requests</h2>
        {requests.length === 0 ? (
          <p className="text-sm text-gray-500">No pending requests.</p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-200 text-left text-gray-500">
                  <th className="pb-3 font-medium">Employee</th>
                  <th className="pb-3 font-medium">Type</th>
                  <th className="pb-3 font-medium">Dates</th>
                  <th className="pb-3 font-medium">Hours</th>
                  <th className="pb-3 font-medium">Status</th>
                  <th className="pb-3 font-medium">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {requests.map((r) => (
                  <tr key={r.id} className="hover:bg-gray-50">
                    <td className="py-3 font-medium text-gray-800">{r.employee}</td>
                    <td className="py-3 text-gray-600">{r.type}</td>
                    <td className="py-3 text-gray-600 whitespace-nowrap text-xs">
                      {r.startDate}{r.startDate !== r.endDate ? ` — ${r.endDate}` : ""}
                    </td>
                    <td className="py-3 text-gray-600">{r.hours} hrs</td>
                    <td className="py-3">
                      <span className={cn("text-xs px-2 py-0.5 rounded-full font-medium", getStatusColor(r.status))}>
                        {r.status}
                      </span>
                    </td>
                    <td className="py-3">
                      <div className="flex items-center gap-2">
                        <button className="flex items-center gap-1 text-xs font-medium text-green-700 bg-green-50 px-3 py-1 rounded-lg hover:bg-green-100 transition-colors">
                          <CheckCircle className="h-3.5 w-3.5" /> Approve
                        </button>
                        <button className="flex items-center gap-1 text-xs font-medium text-red-700 bg-red-50 px-3 py-1 rounded-lg hover:bg-red-100 transition-colors">
                          <XCircle className="h-3.5 w-3.5" /> Deny
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Request History */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <h2 className="text-lg font-semibold text-gray-900 mb-4">Request History</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-200 text-left text-gray-500">
                <th className="pb-3 font-medium">Employee</th>
                <th className="pb-3 font-medium">Type</th>
                <th className="pb-3 font-medium">Dates</th>
                <th className="pb-3 font-medium">Hours</th>
                <th className="pb-3 font-medium">Status</th>
                <th className="pb-3 font-medium">Approved By</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {requestHistory.map((r) => (
                <tr key={r.id} className="hover:bg-gray-50">
                  <td className="py-3 font-medium text-gray-800">{r.employee}</td>
                  <td className="py-3 text-gray-600">{r.type}</td>
                  <td className="py-3 text-gray-600 whitespace-nowrap text-xs">
                    {r.startDate}{r.startDate !== r.endDate ? ` — ${r.endDate}` : ""}
                  </td>
                  <td className="py-3 text-gray-600">{r.hours} hrs</td>
                  <td className="py-3">
                    <span className={cn("text-xs px-2 py-0.5 rounded-full font-medium", getStatusColor(r.status))}>
                      {r.status}
                    </span>
                  </td>
                  <td className="py-3 text-gray-600">{r.approvedBy}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Privacy Notice */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <div className="flex items-start gap-3">
          <ShieldAlert className="h-5 w-5 text-gray-400 mt-0.5 shrink-0" />
          <p className="text-xs text-gray-500">
            FMLA details restricted to HR Administrator access per FMLA &sect;825. Leave records are maintained in
            compliance with applicable federal and state regulations.
          </p>
        </div>
      </div>
    </div>
  );
}
