// Generated by AI. Requires qualified professional review.
"use client";

import { useState } from "react";
import { cn, getStatusColor } from "@/lib/utils";
import {
  ClipboardCheck,
  Star,
  FileText,
  UserCheck,
  CheckCircle2,
  Eye,
  ArrowRight,
  ShieldCheck,
  Calendar,
} from "lucide-react";

const reviewCycle = {
  name: "2026 Annual Review",
  startDate: "Jan 1, 2026",
  endDate: "Dec 31, 2026",
  status: "active",
};

const reviews = [
  { id: 1, employee: "Dr. Sarah Chen", reviewer: "Tyler Ford", cycle: "2026 Annual Review", status: "manager_review", rating: null, ratingLabel: null, dueDate: "Apr 30, 2026" },
  { id: 2, employee: "Amy Rodriguez", reviewer: "Dr. Sarah Chen", cycle: "2026 Annual Review", status: "self_assessment", rating: null, ratingLabel: null, dueDate: "Apr 15, 2026" },
  { id: 3, employee: "Mark Thompson", reviewer: "Tyler Ford", cycle: "2026 Annual Review", status: "draft", rating: null, ratingLabel: null, dueDate: "Apr 30, 2026" },
  { id: 4, employee: "James Wilson", reviewer: "Dr. Sarah Chen", cycle: "2026 Annual Review", status: "approved", rating: 4, ratingLabel: "Exceeds Expectations", dueDate: "Mar 31, 2026" },
  { id: 5, employee: "Lisa Park", reviewer: "Tyler Ford", cycle: "2026 Annual Review", status: "acknowledged", rating: 3, ratingLabel: "Meets Expectations", dueDate: "Mar 31, 2026" },
];

const stages = ["Draft", "Self-Assessment", "Manager Review", "Calibration", "Approved", "Acknowledged"];

const statusCounts = [
  { label: "Draft", value: 1, color: "text-gray-600", bg: "bg-gray-50", icon: FileText },
  { label: "Self-Assessment", value: 1, color: "text-blue-600", bg: "bg-blue-50", icon: ClipboardCheck },
  { label: "Manager Review", value: 1, color: "text-amber-600", bg: "bg-amber-50", icon: UserCheck },
  { label: "Approved", value: 1, color: "text-green-600", bg: "bg-green-50", icon: CheckCircle2 },
  { label: "Acknowledged", value: 1, color: "text-purple-600", bg: "bg-purple-50", icon: Eye },
];

function getReviewStatusColor(status: string): string {
  const colors: Record<string, string> = {
    draft: "bg-gray-100 text-gray-800",
    self_assessment: "bg-blue-100 text-blue-800",
    manager_review: "bg-amber-100 text-amber-800",
    calibration: "bg-indigo-100 text-indigo-800",
    approved: "bg-green-100 text-green-800",
    acknowledged: "bg-purple-100 text-purple-800",
  };
  return colors[status] || getStatusColor(status);
}

function formatStatus(status: string): string {
  return status
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

export function PerformanceTab() {
  return (
    <div className="space-y-6">
      {/* Review Cycle Info */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-blue-50 rounded-lg">
              <ClipboardCheck className="h-5 w-5 text-blue-600" />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-gray-900">{reviewCycle.name}</h2>
              <p className="text-sm text-gray-500 flex items-center gap-2">
                <Calendar className="h-3.5 w-3.5" />
                {reviewCycle.startDate} — {reviewCycle.endDate}
              </p>
            </div>
          </div>
          <span className={cn("text-xs px-2.5 py-1 rounded-full font-medium", getStatusColor(reviewCycle.status))}>
            Active
          </span>
        </div>
      </div>

      {/* Status Overview Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-4">
        {statusCounts.map((card) => (
          <div key={card.label} className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
            <div className="flex items-center gap-3">
              <div className={cn("p-2 rounded-lg", card.bg)}>
                <card.icon className={cn("h-5 w-5", card.color)} />
              </div>
              <div>
                <p className="text-xs text-gray-500">{card.label}</p>
                <p className="text-2xl font-semibold text-gray-900">{card.value}</p>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Status Workflow Indicator */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <h3 className="text-sm font-semibold text-gray-700 mb-4">Review Workflow</h3>
        <div className="flex items-center justify-between">
          {stages.map((stage, i) => (
            <div key={stage} className="flex items-center">
              <div className="flex flex-col items-center">
                <div
                  className={cn(
                    "w-8 h-8 rounded-full flex items-center justify-center text-xs font-medium",
                    i <= 4 ? "bg-blue-100 text-blue-700" : "bg-gray-100 text-gray-500"
                  )}
                >
                  {i + 1}
                </div>
                <span className="text-xs text-gray-500 mt-1.5 whitespace-nowrap">{stage}</span>
              </div>
              {i < stages.length - 1 && (
                <ArrowRight className="h-4 w-4 text-gray-300 mx-2 mb-5" />
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Reviews Table */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <h2 className="text-lg font-semibold text-gray-900 mb-4">Performance Reviews</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-200 text-left text-gray-500">
                <th className="pb-3 font-medium">Employee</th>
                <th className="pb-3 font-medium">Reviewer</th>
                <th className="pb-3 font-medium">Cycle</th>
                <th className="pb-3 font-medium">Status</th>
                <th className="pb-3 font-medium">Rating</th>
                <th className="pb-3 font-medium">Due Date</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {reviews.map((r) => (
                <tr key={r.id} className="hover:bg-gray-50">
                  <td className="py-3 font-medium text-gray-800">{r.employee}</td>
                  <td className="py-3 text-gray-600">{r.reviewer}</td>
                  <td className="py-3 text-gray-600 text-xs">{r.cycle}</td>
                  <td className="py-3">
                    <span className={cn("text-xs px-2 py-0.5 rounded-full font-medium", getReviewStatusColor(r.status))}>
                      {formatStatus(r.status)}
                    </span>
                  </td>
                  <td className="py-3 text-gray-600">
                    {r.rating ? (
                      <span className="flex items-center gap-1">
                        <Star className="h-3.5 w-3.5 text-amber-500 fill-amber-500" />
                        <span className="font-medium">{r.rating}</span>
                        <span className="text-xs text-gray-400">— {r.ratingLabel}</span>
                      </span>
                    ) : (
                      <span className="text-xs text-gray-400">Pending</span>
                    )}
                  </td>
                  <td className="py-3 text-gray-500 text-xs whitespace-nowrap">{r.dueDate}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* James Wilson Detail Panel */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <div className="flex items-center gap-3 mb-5">
          <div className="p-2 bg-green-50 rounded-lg">
            <CheckCircle2 className="h-5 w-5 text-green-600" />
          </div>
          <div>
            <h2 className="text-lg font-semibold text-gray-900">James Wilson — Completed Review</h2>
            <p className="text-sm text-gray-500">2026 Annual Review &middot; Reviewed by Dr. Sarah Chen</p>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Rating */}
          <div>
            <h3 className="text-sm font-semibold text-gray-700 mb-3 flex items-center gap-2">
              <Star className="h-4 w-4 text-amber-500" /> Overall Rating
            </h3>
            <div className="bg-green-50 border border-green-200 rounded-lg p-4 text-center">
              <div className="flex items-center justify-center gap-1 mb-1">
                {[1, 2, 3, 4].map((s) => (
                  <Star key={s} className="h-5 w-5 text-amber-500 fill-amber-500" />
                ))}
                <Star className="h-5 w-5 text-gray-300" />
              </div>
              <p className="text-lg font-semibold text-gray-900">4 — Exceeds Expectations</p>
            </div>
          </div>

          {/* Strengths & Development */}
          <div>
            <h3 className="text-sm font-semibold text-gray-700 mb-3">Strengths</h3>
            <ul className="space-y-1.5 text-sm text-gray-600">
              <li className="flex items-start gap-2">
                <CheckCircle2 className="h-4 w-4 text-green-500 mt-0.5 shrink-0" />
                Strong technical knowledge of QA processes and FDA requirements
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle2 className="h-4 w-4 text-green-500 mt-0.5 shrink-0" />
                Excellent attention to detail in audit documentation
              </li>
              <li className="flex items-start gap-2">
                <CheckCircle2 className="h-4 w-4 text-green-500 mt-0.5 shrink-0" />
                Proactive in identifying and escalating quality issues
              </li>
            </ul>
          </div>

          <div>
            <h3 className="text-sm font-semibold text-gray-700 mb-3">Development Areas</h3>
            <ul className="space-y-1.5 text-sm text-gray-600">
              <li className="flex items-start gap-2">
                <ArrowRight className="h-4 w-4 text-blue-500 mt-0.5 shrink-0" />
                Develop leadership skills for team mentoring
              </li>
              <li className="flex items-start gap-2">
                <ArrowRight className="h-4 w-4 text-blue-500 mt-0.5 shrink-0" />
                Complete Internal Auditing certification (overdue)
              </li>
            </ul>

            <div className="mt-4 pt-4 border-t border-gray-100">
              <div className="space-y-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-gray-500">Approved Date</span>
                  <span className="text-gray-800">Mar 28, 2026</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-500">E-Signature</span>
                  <span className="text-gray-800 text-xs">SIG-2026-00047 (Dr. Sarah Chen)</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Regulatory Note */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <div className="flex items-start gap-3">
          <ShieldCheck className="h-5 w-5 text-gray-400 mt-0.5 shrink-0" />
          <p className="text-xs text-gray-500">
            FDA 21 CFR Part 11 — Electronic signatures on approved reviews are legally binding and
            maintained as part of the quality management system record. All review actions are logged
            in the audit trail with timestamp, user identity, and meaning of signature.
          </p>
        </div>
      </div>
    </div>
  );
}
