// Generated by AI. Requires qualified professional review.
"use client";

import { cn, getStatusColor } from "@/lib/utils";
import { KeyRound } from "lucide-react";

const roles = [
  { id: 1, name: "Super Admin", type: "system", userCount: 1, description: "Full system access with all administrative privileges" },
  { id: 2, name: "QA Manager", type: "system", userCount: 1, description: "Manages quality events, CAPAs, audits, and approvals" },
  { id: 3, name: "Document Controller", type: "system", userCount: 1, description: "Controls document lifecycle, versioning, and distribution" },
  { id: 4, name: "Engineer", type: "system", userCount: 1, description: "Design and engineering access with change control capabilities" },
  { id: 5, name: "Regulatory Specialist", type: "system", userCount: 1, description: "Manages regulatory submissions, filings, and compliance tracking" },
  { id: 6, name: "Viewer", type: "system", userCount: 1, description: "Read-only access across all modules" },
  { id: 7, name: "Department Head", type: "system", userCount: 1, description: "Department-level management with approval authority" },
  { id: 8, name: "QA Auditor", type: "custom", userCount: 0, description: "View all modules, edit Quality and Audit Trail" },
  { id: 9, name: "Label Reviewer", type: "custom", userCount: 0, description: "View all modules, approve Labeling records" },
];

const modules = [
  "Quality",
  "Regulatory",
  "Design",
  "Production",
  "Documents",
  "Labeling",
  "Clinical",
  "Training",
  "Supply Chain",
  "Audit Trail",
  "AI",
  "Admin",
];

type PermLevel = "admin" | "approve" | "edit" | "view" | "none";

const permissionMatrix: Record<string, Record<string, PermLevel>> = {
  "Super Admin": Object.fromEntries(modules.map((m) => [m, "admin"])),
  "QA Manager": {
    Quality: "admin", Regulatory: "view", Design: "view", Production: "view",
    Documents: "approve", Labeling: "view", Clinical: "view", Training: "edit",
    "Supply Chain": "view", "Audit Trail": "view", AI: "edit", Admin: "none",
  },
  "Document Controller": {
    Quality: "view", Regulatory: "view", Design: "view", Production: "view",
    Documents: "admin", Labeling: "edit", Clinical: "view", Training: "edit",
    "Supply Chain": "view", "Audit Trail": "view", AI: "view", Admin: "none",
  },
  Engineer: {
    Quality: "edit", Regulatory: "view", Design: "admin", Production: "edit",
    Documents: "edit", Labeling: "view", Clinical: "view", Training: "view",
    "Supply Chain": "view", "Audit Trail": "view", AI: "edit", Admin: "none",
  },
  "Regulatory Specialist": {
    Quality: "view", Regulatory: "admin", Design: "view", Production: "view",
    Documents: "edit", Labeling: "approve", Clinical: "edit", Training: "view",
    "Supply Chain": "view", "Audit Trail": "view", AI: "view", Admin: "none",
  },
  Viewer: Object.fromEntries(modules.map((m) => [m, "view"])),
  "Department Head": {
    Quality: "approve", Regulatory: "approve", Design: "approve", Production: "approve",
    Documents: "approve", Labeling: "approve", Clinical: "approve", Training: "approve",
    "Supply Chain": "approve", "Audit Trail": "view", AI: "view", Admin: "none",
  },
  "QA Auditor": {
    Quality: "edit", Regulatory: "view", Design: "view", Production: "view",
    Documents: "view", Labeling: "view", Clinical: "view", Training: "view",
    "Supply Chain": "view", "Audit Trail": "edit", AI: "view", Admin: "none",
  },
  "Label Reviewer": {
    Quality: "view", Regulatory: "view", Design: "view", Production: "view",
    Documents: "view", Labeling: "approve", Clinical: "view", Training: "view",
    "Supply Chain": "view", "Audit Trail": "view", AI: "view", Admin: "none",
  },
};

function getPermColor(level: PermLevel) {
  switch (level) {
    case "admin":
    case "approve":
      return "bg-green-100 text-green-800";
    case "edit":
      return "bg-blue-100 text-blue-800";
    case "view":
      return "bg-gray-100 text-gray-600";
    case "none":
      return "bg-white text-gray-300";
  }
}

export function RolesTab() {
  return (
    <div className="space-y-6">
      {/* Roles List */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <h2 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
          <KeyRound className="h-5 w-5 text-gray-400" /> Roles
        </h2>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-200 text-left text-gray-500">
                <th className="pb-3 font-medium">Role Name</th>
                <th className="pb-3 font-medium">Type</th>
                <th className="pb-3 font-medium">Users</th>
                <th className="pb-3 font-medium">Description</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {roles.map((r) => (
                <tr key={r.id} className="hover:bg-gray-50">
                  <td className="py-3 font-medium text-gray-800">{r.name}</td>
                  <td className="py-3">
                    <span
                      className={cn(
                        "text-xs px-2 py-0.5 rounded-full font-medium",
                        r.type === "system"
                          ? "bg-blue-100 text-blue-700"
                          : "bg-purple-100 text-purple-700"
                      )}
                    >
                      {r.type}
                    </span>
                  </td>
                  <td className="py-3 text-gray-600">{r.userCount}</td>
                  <td className="py-3 text-gray-500">{r.description}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Permission Matrix */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <h2 className="text-lg font-semibold text-gray-900 mb-4">Permission Matrix</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-xs">
            <thead>
              <tr className="border-b border-gray-200 text-left text-gray-500">
                <th className="pb-3 pr-3 font-medium sticky left-0 bg-white">Role</th>
                {modules.map((m) => (
                  <th key={m} className="pb-3 px-2 font-medium text-center whitespace-nowrap">
                    {m}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {roles.map((r) => (
                <tr key={r.id} className="hover:bg-gray-50">
                  <td className="py-2 pr-3 font-medium text-gray-800 whitespace-nowrap sticky left-0 bg-white">
                    {r.name}
                  </td>
                  {modules.map((m) => {
                    const level = permissionMatrix[r.name]?.[m] || "none";
                    return (
                      <td key={m} className="py-2 px-2 text-center">
                        <span
                          className={cn(
                            "inline-block px-2 py-0.5 rounded text-xs font-medium",
                            getPermColor(level as PermLevel)
                          )}
                        >
                          {level}
                        </span>
                      </td>
                    );
                  })}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="mt-4 flex flex-wrap gap-4 text-xs text-gray-500">
          <span className="flex items-center gap-1.5"><span className="h-3 w-6 rounded bg-green-100" /> Admin / Approve</span>
          <span className="flex items-center gap-1.5"><span className="h-3 w-6 rounded bg-blue-100" /> Edit</span>
          <span className="flex items-center gap-1.5"><span className="h-3 w-6 rounded bg-gray-100" /> View</span>
          <span className="flex items-center gap-1.5"><span className="h-3 w-6 rounded border border-gray-200" /> None</span>
        </div>
      </div>
    </div>
  );
}
