// Generated by AI. Requires qualified professional review.
"use client";

import { useState } from "react";
import { cn, getStatusColor } from "@/lib/utils";
import {
  GraduationCap,
  AlertTriangle,
  AlertCircle,
  CheckCircle2,
  Clock,
  BookOpen,
  ShieldCheck,
} from "lucide-react";

const trainingAssignments = [
  { id: 1, employee: "Tyler Ford", training: "FDA 21 CFR Part 11", category: "Regulatory", status: "completed", assigned: "Feb 2025", due: null, completed: "Feb 2025", expires: "Feb 2027" },
  { id: 2, employee: "Tyler Ford", training: "ISO 13485 QMS Overview", category: "Quality", status: "completed", assigned: "Feb 2025", due: null, completed: "Feb 2025", expires: "Feb 2027" },
  { id: 3, employee: "Dr. Sarah Chen", training: "CAPA Management", category: "Quality", status: "completed", assigned: "Mar 2025", due: null, completed: "Mar 2025", expires: null },
  { id: 4, employee: "Dr. Sarah Chen", training: "GMP Fundamentals", category: "Quality", status: "completed", assigned: "Mar 2025", due: null, completed: "Mar 2025", expires: "Mar 2027" },
  { id: 5, employee: "Amy Rodriguez", training: "Document Control SOP", category: "Quality", status: "completed", assigned: "Apr 2025", due: null, completed: "Apr 2025", expires: null },
  { id: 6, employee: "Mark Thompson", training: "Design Controls (820.30)", category: "Regulatory", status: "in_progress", assigned: "Mar 2026", due: "Apr 15, 2026", completed: null, expires: null },
  { id: 7, employee: "James Wilson", training: "Internal Auditing", category: "Quality", status: "overdue", assigned: "Jan 2026", due: "Mar 31, 2026", completed: null, expires: null },
  { id: 8, employee: "Lisa Park", training: "EU MDR Fundamentals", category: "Regulatory", status: "assigned", assigned: "Mar 2026", due: "May 1, 2026", completed: null, expires: null },
  { id: 9, employee: "Cynthia Ramirez", training: "GMP Fundamentals", category: "Quality", status: "overdue", assigned: "Dec 2025", due: "Feb 28, 2026", completed: null, expires: null },
  { id: 10, employee: "Robert Kim", training: "Clinical Evidence Review", category: "Regulatory", status: "in_progress", assigned: "Mar 2026", due: "Apr 30, 2026", completed: null, expires: null },
];

const overdueItems = trainingAssignments.filter((t) => t.status === "overdue");
const expiringItems = [
  { employee: "Tyler Ford", training: "FDA 21 CFR Part 11", expires: "Feb 2027" },
  { employee: "Tyler Ford", training: "ISO 13485 QMS Overview", expires: "Feb 2027" },
  { employee: "Dr. Sarah Chen", training: "GMP Fundamentals", expires: "Mar 2027" },
];

const summaryCards = [
  { label: "Total Assignments", value: "10", icon: BookOpen, color: "text-blue-600", bg: "bg-blue-50" },
  { label: "Completed", value: "5 (50%)", icon: CheckCircle2, color: "text-green-600", bg: "bg-green-50" },
  { label: "Overdue", value: "2", icon: AlertCircle, color: "text-red-600", bg: "bg-red-50" },
  { label: "Expiring Soon", value: "2", icon: Clock, color: "text-amber-600", bg: "bg-amber-50" },
];

function getTrainingStatusColor(status: string): string {
  const colors: Record<string, string> = {
    completed: "bg-green-100 text-green-800",
    in_progress: "bg-blue-100 text-blue-800",
    overdue: "bg-red-100 text-red-800",
    assigned: "bg-gray-100 text-gray-800",
  };
  return colors[status] || getStatusColor(status);
}

export function TrainingCertsTab() {
  return (
    <div className="space-y-6">
      {/* Summary Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {summaryCards.map((card) => (
          <div key={card.label} className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
            <div className="flex items-center gap-3">
              <div className={cn("p-2 rounded-lg", card.bg)}>
                <card.icon className={cn("h-5 w-5", card.color)} />
              </div>
              <div>
                <p className="text-sm text-gray-500">{card.label}</p>
                <p className="text-2xl font-semibold text-gray-900">{card.value}</p>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Overdue Alert */}
      <div className="bg-red-50 border border-red-200 rounded-xl p-5">
        <div className="flex items-start gap-3">
          <AlertCircle className="h-5 w-5 text-red-600 mt-0.5 shrink-0" />
          <div>
            <h3 className="text-sm font-semibold text-red-800 mb-2">Overdue Training</h3>
            <ul className="space-y-1">
              {overdueItems.map((item) => (
                <li key={item.id} className="text-sm text-red-700">
                  <span className="font-medium">{item.employee}</span> — {item.training} (due {item.due})
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      {/* Expiring Certifications Alert */}
      <div className="bg-amber-50 border border-amber-200 rounded-xl p-5">
        <div className="flex items-start gap-3">
          <AlertTriangle className="h-5 w-5 text-amber-600 mt-0.5 shrink-0" />
          <div>
            <h3 className="text-sm font-semibold text-amber-800 mb-2">Expiring Certifications</h3>
            <ul className="space-y-1">
              {expiringItems.map((item, i) => (
                <li key={i} className="text-sm text-amber-700">
                  <span className="font-medium">{item.employee}</span> — {item.training} (expires {item.expires})
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      {/* Training Table */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <h2 className="text-lg font-semibold text-gray-900 mb-4">All Training Assignments</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-200 text-left text-gray-500">
                <th className="pb-3 font-medium">Employee</th>
                <th className="pb-3 font-medium">Training</th>
                <th className="pb-3 font-medium">Category</th>
                <th className="pb-3 font-medium">Status</th>
                <th className="pb-3 font-medium">Assigned</th>
                <th className="pb-3 font-medium">Due</th>
                <th className="pb-3 font-medium">Completed</th>
                <th className="pb-3 font-medium">Expires</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {trainingAssignments.map((t) => (
                <tr key={t.id} className="hover:bg-gray-50">
                  <td className="py-3 font-medium text-gray-800">{t.employee}</td>
                  <td className="py-3 text-gray-600">{t.training}</td>
                  <td className="py-3 text-gray-600">{t.category}</td>
                  <td className="py-3">
                    <span className={cn("text-xs px-2 py-0.5 rounded-full font-medium", getTrainingStatusColor(t.status))}>
                      {t.status.replace("_", " ")}
                    </span>
                  </td>
                  <td className="py-3 text-gray-500 text-xs whitespace-nowrap">{t.assigned}</td>
                  <td className="py-3 text-gray-500 text-xs whitespace-nowrap">{t.due || "—"}</td>
                  <td className="py-3 text-gray-500 text-xs whitespace-nowrap">{t.completed || "—"}</td>
                  <td className="py-3 text-gray-500 text-xs whitespace-nowrap">{t.expires || "No expiry"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Regulatory Note */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <div className="flex items-start gap-3">
          <ShieldCheck className="h-5 w-5 text-gray-400 mt-0.5 shrink-0" />
          <p className="text-xs text-gray-500">
            ISO 13485 &sect;6.2.2 / 21 CFR 820.25(b) — Training records maintained for audit readiness.
            All training completions are electronically signed and timestamped per 21 CFR Part 11.
          </p>
        </div>
      </div>
    </div>
  );
}
