// Generated by AI. Requires qualified professional review.
"use client";

import { useState } from "react";
import { cn, getStatusColor } from "@/lib/utils";
import { Search, User, Mail, Clock, Shield, Activity } from "lucide-react";

const users = [
  { id: 1, name: "Tyler Ford", email: "tyler@meddev.com", department: "Management", role: "Super Admin", status: "active", lastLogin: "Apr 2, 2026 09:15 AM" },
  { id: 2, name: "Dr. Sarah Chen", email: "sarah@meddev.com", department: "Quality", role: "QA Manager", status: "active", lastLogin: "Apr 2, 2026 08:42 AM" },
  { id: 3, name: "Amy Rodriguez", email: "amy@meddev.com", department: "Document Control", role: "Document Controller", status: "active", lastLogin: "Apr 1, 2026 04:30 PM" },
  { id: 4, name: "Mark Thompson", email: "mark@meddev.com", department: "Design & Engineering", role: "Engineer", status: "active", lastLogin: "Apr 2, 2026 10:05 AM" },
  { id: 5, name: "James Wilson", email: "james@meddev.com", department: "Quality", role: "QA Approver", status: "active", lastLogin: "Apr 2, 2026 07:58 AM" },
  { id: 6, name: "Lisa Park", email: "lisa@meddev.com", department: "Regulatory", role: "Regulatory Specialist", status: "active", lastLogin: "Apr 1, 2026 03:12 PM" },
  { id: 7, name: "Cynthia Ramirez", email: "cynthia@meddev.com", department: "Production", role: "Viewer", status: "active", lastLogin: "Mar 31, 2026 11:40 AM" },
  { id: 8, name: "Robert Kim", email: "robert@meddev.com", department: "Clinical", role: "Department Head", status: "active", lastLogin: "Apr 1, 2026 02:20 PM" },
];

const tylerDetail = {
  roleHistory: [
    { role: "Super Admin", assignedBy: "System", date: "Jan 15, 2025", note: "Initial setup" },
    { role: "QA Manager", assignedBy: "System", date: "Jan 10, 2025", note: "Temporary assignment during onboarding" },
  ],
  permissions: ["Full system access", "User management", "Role assignment", "Audit log access", "System configuration", "Data export"],
  recentAudit: [
    { action: "Assigned role QA Approver to James Wilson", timestamp: "Apr 1, 2026 02:30 PM" },
    { action: "Created user Robert Kim", timestamp: "Mar 28, 2026 10:15 AM" },
    { action: "Updated department head for Clinical", timestamp: "Mar 28, 2026 10:20 AM" },
    { action: "Modified permissions for Label Reviewer role", timestamp: "Mar 25, 2026 04:45 PM" },
  ],
};

export function UsersTab() {
  const [search, setSearch] = useState("");

  const filtered = users.filter(
    (u) =>
      u.name.toLowerCase().includes(search.toLowerCase()) ||
      u.email.toLowerCase().includes(search.toLowerCase()) ||
      u.department.toLowerCase().includes(search.toLowerCase()) ||
      u.role.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="space-y-6">
      {/* Search */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
          <input
            type="text"
            placeholder="Search users by name, email, department, or role..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-10 pr-4 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
        </div>
      </div>

      {/* Users Table */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <h2 className="text-lg font-semibold text-gray-900 mb-4">All Users</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-200 text-left text-gray-500">
                <th className="pb-3 font-medium">Name</th>
                <th className="pb-3 font-medium">Email</th>
                <th className="pb-3 font-medium">Department</th>
                <th className="pb-3 font-medium">Role</th>
                <th className="pb-3 font-medium">Status</th>
                <th className="pb-3 font-medium">Last Login</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {filtered.map((u) => (
                <tr key={u.id} className="hover:bg-gray-50">
                  <td className="py-3 font-medium text-gray-800">{u.name}</td>
                  <td className="py-3 text-gray-600">{u.email}</td>
                  <td className="py-3 text-gray-600">{u.department}</td>
                  <td className="py-3 text-gray-600">{u.role}</td>
                  <td className="py-3">
                    <span className={cn("text-xs px-2 py-0.5 rounded-full font-medium", getStatusColor(u.status))}>
                      {u.status}
                    </span>
                  </td>
                  <td className="py-3 text-gray-500 whitespace-nowrap text-xs">{u.lastLogin}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* User Detail Panel — Tyler Ford */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5">
        <div className="flex items-center gap-3 mb-5">
          <div className="p-2 bg-blue-50 rounded-lg">
            <User className="h-5 w-5 text-blue-600" />
          </div>
          <div>
            <h2 className="text-lg font-semibold text-gray-900">Tyler Ford</h2>
            <p className="text-sm text-gray-500">tyler@meddev.com &middot; Management &middot; Super Admin</p>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Role Assignment Timeline */}
          <div>
            <h3 className="text-sm font-semibold text-gray-700 mb-3 flex items-center gap-2">
              <Shield className="h-4 w-4 text-gray-400" /> Role Assignments
            </h3>
            <div className="space-y-3">
              {tylerDetail.roleHistory.map((r, i) => (
                <div key={i} className="border-l-2 border-blue-200 pl-3">
                  <p className="text-sm font-medium text-gray-800">{r.role}</p>
                  <p className="text-xs text-gray-500">{r.date} &middot; by {r.assignedBy}</p>
                  <p className="text-xs text-gray-400">{r.note}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Permissions Summary */}
          <div>
            <h3 className="text-sm font-semibold text-gray-700 mb-3 flex items-center gap-2">
              <Mail className="h-4 w-4 text-gray-400" /> Permissions Summary
            </h3>
            <ul className="space-y-1.5">
              {tylerDetail.permissions.map((p, i) => (
                <li key={i} className="text-sm text-gray-600 flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-green-500" />
                  {p}
                </li>
              ))}
            </ul>
          </div>

          {/* Recent Audit Entries */}
          <div>
            <h3 className="text-sm font-semibold text-gray-700 mb-3 flex items-center gap-2">
              <Activity className="h-4 w-4 text-gray-400" /> Recent Audit Entries
            </h3>
            <div className="space-y-3">
              {tylerDetail.recentAudit.map((a, i) => (
                <div key={i} className="pb-2 border-b border-gray-100 last:border-0">
                  <p className="text-sm text-gray-700">{a.action}</p>
                  <p className="text-xs text-gray-400 flex items-center gap-1 mt-0.5">
                    <Clock className="h-3 w-3" /> {a.timestamp}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
