// Generated by AI. Requires qualified professional review.
import { NextResponse } from "next/server";

const mockAuditLogs = [
  { id: "LOG-001", action: "USER_CREATED", entity: "User", entityId: "USR-008", performedBy: "Aisha Patel", details: "Created user David Thornton", timestamp: "2026-04-02T07:45:00Z" },
  { id: "LOG-002", action: "ROLE_ASSIGNED", entity: "User", entityId: "USR-008", performedBy: "Aisha Patel", details: "Assigned role Supplier Quality Engineer", timestamp: "2026-04-02T07:46:00Z" },
  { id: "LOG-003", action: "DOCUMENT_APPROVED", entity: "Document", entityId: "DOC-2045", performedBy: "Dr. Sarah Chen", details: "Approved Design Verification Protocol - Rev C", timestamp: "2026-04-01T14:30:00Z" },
  { id: "LOG-004", action: "SIGNATURE_RECORDED", entity: "Signature", entityId: "SIG-001", performedBy: "Dr. Sarah Chen", details: "E-signature on DOC-2045", timestamp: "2026-04-01T14:30:00Z" },
  { id: "LOG-005", action: "LOGIN_SUCCESS", entity: "Session", entityId: "USR-002", performedBy: "James Rodriguez", details: "Successful login from 10.0.1.55", timestamp: "2026-04-01T09:15:00Z" },
  { id: "LOG-006", action: "DELEGATION_CREATED", entity: "Delegation", entityId: "DEL-001", performedBy: "Dr. Sarah Chen", details: "Delegated Quality Manager to Lisa Park", timestamp: "2026-03-28T10:00:00Z" },
  { id: "LOG-007", action: "PERMISSION_UPDATED", entity: "Role", entityId: "ROLE-008", performedBy: "Aisha Patel", details: "Updated permissions for Supplier Quality Engineer", timestamp: "2026-03-27T16:30:00Z" },
  { id: "LOG-008", action: "USER_DEACTIVATED", entity: "User", entityId: "USR-006", performedBy: "Aisha Patel", details: "Deactivated user Robert Müller", timestamp: "2026-03-25T09:00:00Z" },
  { id: "LOG-009", action: "ROLE_CREATED", entity: "Role", entityId: "ROLE-009", performedBy: "Aisha Patel", details: "Created custom role Clinical Specialist", timestamp: "2026-03-24T11:00:00Z" },
  { id: "LOG-010", action: "DEPARTMENT_UPDATED", entity: "Department", entityId: "DEPT-003", performedBy: "Aisha Patel", details: "Updated head of Engineering department", timestamp: "2026-03-22T14:15:00Z" },
  { id: "LOG-011", action: "LOGIN_FAILED", entity: "Session", entityId: "USR-006", performedBy: "System", details: "Failed login attempt for robert.muller@meddevice.com", timestamp: "2026-03-20T18:30:00Z" },
  { id: "LOG-012", action: "USER_UPDATED", entity: "User", entityId: "USR-001", performedBy: "Aisha Patel", details: "Updated role from Document Controller to Quality Manager", timestamp: "2026-03-20T11:00:00Z" },
  { id: "LOG-013", action: "TRAINING_COMPLETED", entity: "Training", entityId: "TRN-445", performedBy: "System", details: "Training record updated for Emily Watson", timestamp: "2026-03-18T10:00:00Z" },
  { id: "LOG-014", action: "DOCUMENT_RELEASED", entity: "Document", entityId: "DOC-2040", performedBy: "Lisa Park", details: "Released SOP-QA-012 Rev D", timestamp: "2026-03-15T16:00:00Z" },
  { id: "LOG-015", action: "CAPA_OPENED", entity: "CAPA", entityId: "CAPA-0089", performedBy: "Michael Okafor", details: "Opened CAPA for soldering defect trend", timestamp: "2026-03-14T09:30:00Z" },
  { id: "LOG-016", action: "SIGNATURE_RECORDED", entity: "Signature", entityId: "SIG-010", performedBy: "James Rodriguez", details: "E-signature on regulatory submission", timestamp: "2026-03-12T11:45:00Z" },
  { id: "LOG-017", action: "PASSWORD_RESET", entity: "User", entityId: "USR-005", performedBy: "Aisha Patel", details: "Admin-initiated password reset for Lisa Park", timestamp: "2026-03-10T08:30:00Z" },
  { id: "LOG-018", action: "ROLE_UPDATED", entity: "Role", entityId: "ROLE-008", performedBy: "Aisha Patel", details: "Updated description for Supplier Quality Engineer", timestamp: "2026-03-08T15:00:00Z" },
  { id: "LOG-019", action: "DEPARTMENT_CREATED", entity: "Department", entityId: "DEPT-006", performedBy: "Aisha Patel", details: "Created Supply Chain department", timestamp: "2026-03-05T10:00:00Z" },
  { id: "LOG-020", action: "LOGIN_SUCCESS", entity: "Session", entityId: "USR-007", performedBy: "Aisha Patel", details: "Successful login from 10.0.1.100", timestamp: "2026-03-03T07:30:00Z" },
];

export async function GET() {
  return NextResponse.json({
    auditLogs: mockAuditLogs,
    total: mockAuditLogs.length,
  });
}
