// Generated by AI. Requires qualified professional review.
import { NextResponse } from "next/server";

const mockTrainingAssignments = [
  { id: "tr-001", employeeId: "emp-001", name: "Alice Johnson", course: "GMP Fundamentals", status: "completed", assignedDate: "2025-12-01", completedDate: "2025-12-20", expiresAt: "2026-12-20" },
  { id: "tr-002", employeeId: "emp-002", name: "Bob Smith", course: "ISO 13485 Overview", status: "in_progress", assignedDate: "2026-02-15", dueDate: "2026-04-15", completedDate: null, expiresAt: null },
  { id: "tr-003", employeeId: "emp-003", name: "Carol Davis", course: "Risk Management (ISO 14971)", status: "completed", assignedDate: "2025-10-01", completedDate: "2025-11-01", expiresAt: "2026-11-01" },
  { id: "tr-004", employeeId: "emp-004", name: "Dan Wilson", course: "CAPA Procedures", status: "overdue", assignedDate: "2025-11-01", dueDate: "2026-01-31", completedDate: null, expiresAt: null },
  { id: "tr-005", employeeId: "emp-005", name: "Eva Martinez", course: "Document Control", status: "completed", assignedDate: "2026-01-10", completedDate: "2026-02-05", expiresAt: "2027-02-05" },
  { id: "tr-006", employeeId: "emp-006", name: "Frank Lee", course: "GMP Fundamentals", status: "not_started", assignedDate: "2026-03-15", dueDate: "2026-05-15", completedDate: null, expiresAt: null },
  { id: "tr-007", employeeId: "emp-007", name: "Grace Chen", course: "Design Controls", status: "completed", assignedDate: "2025-09-01", completedDate: "2025-10-15", expiresAt: "2026-10-15" },
  { id: "tr-008", employeeId: "emp-008", name: "Hank Brown", course: "FDA 21 CFR Part 820", status: "in_progress", assignedDate: "2026-03-01", dueDate: "2026-05-01", completedDate: null, expiresAt: null },
  { id: "tr-009", employeeId: "emp-001", name: "Alice Johnson", course: "Cleanroom Procedures", status: "completed", assignedDate: "2026-01-15", completedDate: "2026-02-10", expiresAt: "2027-02-10" },
  { id: "tr-010", employeeId: "emp-003", name: "Carol Davis", course: "Supplier Quality Management", status: "overdue", assignedDate: "2025-12-01", dueDate: "2026-02-28", completedDate: null, expiresAt: null },
];

export async function GET() {
  return NextResponse.json({ data: mockTrainingAssignments, total: mockTrainingAssignments.length });
}

export async function POST() {
  return NextResponse.json({ success: true, message: "Training assigned" });
}
