// Generated by AI. Requires qualified professional review.
import { db } from "@/server/db";
import { auditLogs } from "@/server/db/schema";

export type AuditAction =
  | "create"
  | "update"
  | "delete"
  | "deactivate"
  | "reactivate"
  | "assign"
  | "revoke"
  | "sign"
  | "approve"
  | "reject"
  | "submit"
  | "archive"
  | "login"
  | "export"
  | "delegate";

interface LogAuditEventParams {
  tenantId: string;
  userId: string;
  action: AuditAction;
  entityType: string; // "user" | "role" | "department" | "permission" | "delegation" | "signature" | "document" | "capa" etc.
  entityId: string;
  module?: string; // "admin" | "quality" | "documents" | "regulatory" etc.
  oldValue?: Record<string, any> | null; // JSON snapshot before change (null for creates)
  newValue?: Record<string, any> | null; // JSON snapshot after change (null for deletes)
  ipAddress?: string | null;
  userAgent?: string | null;
  sessionId?: string | null; // Groups related changes
}

/**
 * Log an audit event. Called by every API route that mutates data.
 * Audit logs are append-only and protected by database trigger (21 CFR Part 11).
 */
export async function logAuditEvent(params: LogAuditEventParams) {
  const changes: Record<string, any> = {};

  if (params.oldValue !== undefined) changes.oldValue = params.oldValue;
  if (params.newValue !== undefined) changes.newValue = params.newValue;
  if (params.module) changes.module = params.module;
  if (params.sessionId) changes.sessionId = params.sessionId;

  await db.insert(auditLogs).values({
    tenantId: params.tenantId,
    userId: params.userId,
    action: params.action,
    entityType: params.entityType,
    entityId: params.entityId,
    changes: Object.keys(changes).length > 0 ? changes : null,
    ipAddress: params.ipAddress ?? null,
    userAgent: params.userAgent ?? null,
  });
}

// Legacy alias for backwards compatibility
export const logAudit = logAuditEvent;
