// Generated by AI. Requires qualified professional review.
import { db } from "@/server/db";
import { rolePermissions, userRoleAssignments, delegations } from "@/server/db/schema";
import { eq, and, gte, lte, or } from "drizzle-orm";

export type Module =
  | "admin"
  | "quality"
  | "regulatory"
  | "design"
  | "production"
  | "documents"
  | "labeling"
  | "clinical"
  | "training"
  | "supply_chain"
  | "audit_trail"
  | "ai";

export type PermissionLevel = "none" | "view" | "edit" | "approve" | "admin";

const PERMISSION_HIERARCHY: Record<PermissionLevel, number> = {
  none: 0,
  view: 1,
  edit: 2,
  approve: 3,
  admin: 4,
};

/**
 * Check if a user has at least the required permission level for a module.
 * Considers: direct role assignments + active delegations.
 * Training gate: if assignment has trainingRequired=true and trainingCompletedAt is null, skip it.
 */
export async function checkPermission(
  tenantId: string,
  userId: string,
  module: Module,
  requiredLevel: PermissionLevel
): Promise<boolean> {
  const now = new Date();

  // 1. Get user's active role assignments (respecting training gate)
  const assignments = await db
    .select()
    .from(userRoleAssignments)
    .where(
      and(
        eq(userRoleAssignments.tenantId, tenantId),
        eq(userRoleAssignments.userId, userId),
        eq(userRoleAssignments.status, "active"),
        lte(userRoleAssignments.effectiveStart, now),
        or(
          eq(userRoleAssignments.effectiveEnd, null as any),
          gte(userRoleAssignments.effectiveEnd, now)
        )
      )
    );

  // Filter out assignments that require training but haven't completed it
  const effectiveAssignments = assignments.filter(
    (a) => !a.trainingRequired || a.trainingCompletedAt !== null
  );

  const roleIds = effectiveAssignments.map((a) => a.roleId);

  // 2. Check permissions for each role
  for (const roleId of roleIds) {
    const perms = await db
      .select()
      .from(rolePermissions)
      .where(
        and(
          eq(rolePermissions.tenantId, tenantId),
          eq(rolePermissions.roleId, roleId),
          eq(rolePermissions.module, module)
        )
      );

    for (const perm of perms) {
      const level = perm.permissionLevel as PermissionLevel;
      if (PERMISSION_HIERARCHY[level] >= PERMISSION_HIERARCHY[requiredLevel]) {
        return true;
      }
    }
  }

  // 3. Check active delegations
  const activeDelegations = await db
    .select()
    .from(delegations)
    .where(
      and(
        eq(delegations.tenantId, tenantId),
        eq(delegations.delegateId, userId),
        eq(delegations.module, module),
        eq(delegations.status, "active"),
        lte(delegations.startDate, now),
        gte(delegations.endDate, now)
      )
    );

  if (activeDelegations.length > 0) {
    // Delegate inherits delegator's permissions for the specified module
    for (const del of activeDelegations) {
      const hasPermission = await checkPermission(
        tenantId,
        del.delegatorId,
        module,
        requiredLevel
      );
      if (hasPermission) return true;
    }
  }

  return false;
}

/**
 * Get all effective permissions for a user across all modules.
 */
export async function getUserPermissions(
  tenantId: string,
  userId: string
): Promise<Record<Module, PermissionLevel>> {
  const modules: Module[] = [
    "admin", "quality", "regulatory", "design", "production",
    "documents", "labeling", "clinical", "training", "supply_chain",
    "audit_trail", "ai",
  ];

  const result: Record<string, PermissionLevel> = {};

  for (const mod of modules) {
    if (await checkPermission(tenantId, userId, mod, "admin")) {
      result[mod] = "admin";
    } else if (await checkPermission(tenantId, userId, mod, "approve")) {
      result[mod] = "approve";
    } else if (await checkPermission(tenantId, userId, mod, "edit")) {
      result[mod] = "edit";
    } else if (await checkPermission(tenantId, userId, mod, "view")) {
      result[mod] = "view";
    } else {
      result[mod] = "none";
    }
  }

  return result as Record<Module, PermissionLevel>;
}
