// Generated by AI. Requires qualified professional review.
"use client";

import { useState } from "react";
import { X, ShieldCheck, AlertTriangle } from "lucide-react";
import { cn } from "@/lib/utils";

export type SignatureType = "approval" | "review" | "release" | "change_control" | "delegation";
export type SignatureMeaning = "approved" | "reviewed" | "rejected" | "acknowledged";

interface ESignatureDialogProps {
  isOpen: boolean;
  onClose: () => void;
  onSign: (data: SignatureData) => void;
  entityType: string;
  entityId: string;
  signatureType: SignatureType;
  title?: string;
  description?: string;
}

export interface SignatureData {
  entityType: string;
  entityId: string;
  signatureType: SignatureType;
  meaning: SignatureMeaning;
  reason: string;
  password: string;
  timestamp: string;
}

export function ESignatureDialog({
  isOpen,
  onClose,
  onSign,
  entityType,
  entityId,
  signatureType,
  title = "Electronic Signature Required",
  description = "This action requires electronic signature per 21 CFR Part 11.",
}: ESignatureDialogProps) {
  const [meaning, setMeaning] = useState<SignatureMeaning>("approved");
  const [reason, setReason] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");

  if (!isOpen) return null;

  const handleSign = () => {
    if (!reason.trim()) {
      setError("Reason is required for electronic signatures.");
      return;
    }
    if (!password.trim()) {
      setError("Password re-authentication is required.");
      return;
    }
    setError("");
    onSign({
      entityType,
      entityId,
      signatureType,
      meaning,
      reason: reason.trim(),
      password,
      timestamp: new Date().toISOString(),
    });
    setReason("");
    setPassword("");
    onClose();
  };

  const meanings: { value: SignatureMeaning; label: string }[] = [
    { value: "approved", label: "Approved" },
    { value: "reviewed", label: "Reviewed" },
    { value: "rejected", label: "Rejected" },
    { value: "acknowledged", label: "Acknowledged" },
  ];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
      <div className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl">
        {/* Header */}
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-3">
            <div className="rounded-lg bg-blue-50 p-2">
              <ShieldCheck className="h-5 w-5 text-blue-600" />
            </div>
            <div>
              <h2 className="font-semibold text-gray-900">{title}</h2>
              <p className="text-xs text-gray-500 mt-0.5">{description}</p>
            </div>
          </div>
          <button onClick={onClose} className="rounded-md p-1 hover:bg-gray-100">
            <X className="h-4 w-4 text-gray-400" />
          </button>
        </div>

        {/* Entity Info */}
        <div className="mt-4 rounded-lg bg-gray-50 p-3 text-xs">
          <div className="flex justify-between">
            <span className="text-gray-500">Entity Type</span>
            <span className="font-medium text-gray-700">{entityType}</span>
          </div>
          <div className="flex justify-between mt-1">
            <span className="text-gray-500">Entity ID</span>
            <span className="font-mono text-gray-700">{entityId}</span>
          </div>
          <div className="flex justify-between mt-1">
            <span className="text-gray-500">Signature Type</span>
            <span className="font-medium text-gray-700 capitalize">{signatureType.replace(/_/g, " ")}</span>
          </div>
        </div>

        {/* Meaning Selection */}
        <div className="mt-4">
          <label className="text-sm font-medium text-gray-700">Signature Meaning</label>
          <div className="mt-2 grid grid-cols-2 gap-2">
            {meanings.map((m) => (
              <button
                key={m.value}
                onClick={() => setMeaning(m.value)}
                className={cn(
                  "rounded-lg border px-3 py-2 text-xs font-medium transition-colors",
                  meaning === m.value
                    ? "border-blue-500 bg-blue-50 text-blue-700"
                    : "border-gray-200 bg-white text-gray-600 hover:bg-gray-50"
                )}
              >
                {m.label}
              </button>
            ))}
          </div>
        </div>

        {/* Reason */}
        <div className="mt-4">
          <label className="text-sm font-medium text-gray-700">
            Reason <span className="text-red-500">*</span>
          </label>
          <textarea
            value={reason}
            onChange={(e) => setReason(e.target.value)}
            placeholder="Provide reason for this signature..."
            className="mt-1 w-full rounded-lg border border-gray-200 p-2.5 text-sm outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
            rows={2}
          />
        </div>

        {/* Password Re-authentication */}
        <div className="mt-4">
          <label className="text-sm font-medium text-gray-700">
            Re-authenticate <span className="text-red-500">*</span>
          </label>
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            placeholder="Enter your password to sign"
            className="mt-1 w-full rounded-lg border border-gray-200 p-2.5 text-sm outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
          />
        </div>

        {/* Error */}
        {error && (
          <div className="mt-3 flex items-center gap-2 rounded-lg bg-red-50 p-2.5 text-xs text-red-700">
            <AlertTriangle className="h-3.5 w-3.5 shrink-0" />
            {error}
          </div>
        )}

        {/* Regulatory Notice */}
        <div className="mt-4 rounded-lg bg-amber-50 p-2.5 text-[10px] text-amber-700">
          Per 21 CFR Part 11 §11.50, §11.70, §11.100: This signature constitutes the
          legally binding equivalent of a handwritten signature. It records who signed,
          when, what was signed, and why.
        </div>

        {/* Actions */}
        <div className="mt-4 flex gap-2">
          <button
            onClick={onClose}
            className="flex-1 rounded-lg border border-gray-200 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50"
          >
            Cancel
          </button>
          <button
            onClick={handleSign}
            className="flex-1 rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700"
          >
            Apply Signature
          </button>
        </div>
      </div>
    </div>
  );
}
