// Generated by AI. Requires qualified professional review.
import { NextResponse } from "next/server";

const mockPerformanceReviews = [
  { id: "pr-001", employeeId: "emp-001", name: "Alice Johnson", reviewCycle: "2026 Annual", rating: 4, status: "draft", reviewerId: "mgr-001", createdAt: "2026-03-01" },
  { id: "pr-002", employeeId: "emp-002", name: "Bob Smith", reviewCycle: "2026 Annual", rating: 3, status: "submitted", reviewerId: "mgr-001", createdAt: "2026-03-05" },
  { id: "pr-003", employeeId: "emp-003", name: "Carol Davis", reviewCycle: "2026 Annual", rating: 5, status: "approved", reviewerId: "mgr-002", createdAt: "2026-02-28", approvedAt: "2026-03-20" },
  { id: "pr-004", employeeId: "emp-005", name: "Eva Martinez", reviewCycle: "2026 Annual", rating: 4, status: "acknowledged", reviewerId: "mgr-002", createdAt: "2026-03-01", acknowledgedAt: "2026-03-25" },
  { id: "pr-005", employeeId: "emp-007", name: "Grace Chen", reviewCycle: "2026 Annual", rating: 3, status: "draft", reviewerId: "mgr-003", createdAt: "2026-03-10" },
];

export async function GET() {
  return NextResponse.json({ data: mockPerformanceReviews, total: mockPerformanceReviews.length });
}

export async function POST() {
  return NextResponse.json({ success: true, message: "Performance review created" });
}
