// Generated by AI. Requires qualified professional review.
"use client";

import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type PermissionLevel = "none" | "view" | "edit" | "approve" | "admin";

export type Module =
  | "admin"
  | "quality"
  | "regulatory"
  | "design"
  | "production"
  | "documents"
  | "labeling"
  | "clinical"
  | "training"
  | "supply_chain"
  | "audit_trail"
  | "ai";

interface PermissionsContextType {
  permissions: Record<Module, PermissionLevel>;
  hasPermission: (module: Module, level: PermissionLevel) => boolean;
  isLoading: boolean;
  currentUserId: string | null;
  currentTenantId: string | null;
}

const LEVEL_HIERARCHY: Record<PermissionLevel, number> = {
  none: 0,
  view: 1,
  edit: 2,
  approve: 3,
  admin: 4,
};

// Default: admin on everything (for demo/dev without auth)
const DEFAULT_PERMISSIONS: Record<Module, PermissionLevel> = {
  admin: "admin",
  quality: "admin",
  regulatory: "admin",
  design: "admin",
  production: "admin",
  documents: "admin",
  labeling: "admin",
  clinical: "admin",
  training: "admin",
  supply_chain: "admin",
  audit_trail: "admin",
  ai: "admin",
};

const PermissionsContext = createContext<PermissionsContextType>({
  permissions: DEFAULT_PERMISSIONS,
  hasPermission: () => true,
  isLoading: false,
  currentUserId: null,
  currentTenantId: null,
});

export function PermissionsProvider({ children }: { children: ReactNode }) {
  const [permissions, setPermissions] = useState<Record<Module, PermissionLevel>>(DEFAULT_PERMISSIONS);
  const [isLoading, setIsLoading] = useState(false);

  // In production, this would fetch from /api/admin/check-permission
  // For now, use default admin permissions
  useEffect(() => {
    setPermissions(DEFAULT_PERMISSIONS);
  }, []);

  const hasPermission = (module: Module, level: PermissionLevel): boolean => {
    const userLevel = permissions[module] ?? "none";
    return LEVEL_HIERARCHY[userLevel] >= LEVEL_HIERARCHY[level];
  };

  return (
    <PermissionsContext.Provider
      value={{
        permissions,
        hasPermission,
        isLoading,
        currentUserId: "usr_tyler_ford",
        currentTenantId: "tenant_meddev",
      }}
    >
      {children}
    </PermissionsContext.Provider>
  );
}

export function usePermissions() {
  return useContext(PermissionsContext);
}

/**
 * Conditionally render children based on permission level.
 */
export function RequirePermission({
  module,
  level,
  children,
  fallback = null,
}: {
  module: Module;
  level: PermissionLevel;
  children: ReactNode;
  fallback?: ReactNode;
}) {
  const { hasPermission } = usePermissions();
  return hasPermission(module, level) ? <>{children}</> : <>{fallback}</>;
}
