// Generated by AI. Requires qualified professional review.
import {
  pgTable,
  pgEnum,
  text,
  timestamp,
  boolean,
  integer,
  jsonb,
  index,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// Enums
export const roleTypeEnum = pgEnum("role_type", ["system", "custom"]);
export const permissionLevelEnum = pgEnum("permission_level", [
  "none",
  "view",
  "edit",
  "approve",
  "hr_admin",
  "admin",
]);
export const assignmentStatusEnum = pgEnum("assignment_status", [
  "active",
  "pending_training",
  "expired",
  "revoked",
]);
export const delegationStatusEnum = pgEnum("delegation_status", [
  "active",
  "expired",
  "revoked",
]);
export const signatureTypeEnum = pgEnum("signature_type", [
  "approval",
  "review",
  "release",
  "change_control",
  "delegation",
]);
export const signatureMeaningEnum = pgEnum("signature_meaning", [
  "approved",
  "reviewed",
  "rejected",
  "acknowledged",
]);

// Tables
export const departments = pgTable(
  "departments",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    tenantId: text("tenant_id").notNull(),
    name: text("name").notNull(),
    code: text("code").notNull(),
    description: text("description"),
    headUserId: text("head_user_id"),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [index("departments_tenant_id_idx").on(table.tenantId)]
);

export const roles = pgTable(
  "roles",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    tenantId: text("tenant_id").notNull(),
    name: text("name").notNull(),
    description: text("description"),
    type: roleTypeEnum("type").default("custom").notNull(),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [index("roles_tenant_id_idx").on(table.tenantId)]
);

export const rolePermissions = pgTable(
  "role_permissions",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    tenantId: text("tenant_id").notNull(),
    roleId: text("role_id").notNull(),
    module: text("module").notNull(),
    permissionLevel: permissionLevelEnum("permission_level")
      .default("none")
      .notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("role_permissions_tenant_id_idx").on(table.tenantId),
    index("role_permissions_role_id_idx").on(table.roleId),
  ]
);

export const userRoleAssignments = pgTable(
  "user_role_assignments",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    tenantId: text("tenant_id").notNull(),
    userId: text("user_id").notNull(),
    roleId: text("role_id").notNull(),
    assignedBy: text("assigned_by").notNull(),
    effectiveStart: timestamp("effective_start").notNull(),
    effectiveEnd: timestamp("effective_end"),
    status: assignmentStatusEnum("status").default("active").notNull(),
    trainingRequired: boolean("training_required").default(false).notNull(),
    trainingCompletedAt: timestamp("training_completed_at"),
    notes: text("notes"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("user_role_assignments_tenant_id_idx").on(table.tenantId),
    index("user_role_assignments_user_id_idx").on(table.userId),
  ]
);

export const userDepartmentAssignments = pgTable(
  "user_department_assignments",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    tenantId: text("tenant_id").notNull(),
    userId: text("user_id").notNull(),
    departmentId: text("department_id").notNull(),
    isPrimary: boolean("is_primary").default(false).notNull(),
    assignedBy: text("assigned_by").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("user_dept_assignments_tenant_id_idx").on(table.tenantId),
    index("user_dept_assignments_user_id_idx").on(table.userId),
  ]
);

export const delegations = pgTable(
  "delegations",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    tenantId: text("tenant_id").notNull(),
    delegatorId: text("delegator_id").notNull(),
    delegateId: text("delegate_id").notNull(),
    module: text("module").notNull(),
    reason: text("reason").notNull(),
    startDate: timestamp("start_date").notNull(),
    endDate: timestamp("end_date").notNull(),
    status: delegationStatusEnum("status").default("active").notNull(),
    createdBy: text("created_by").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [index("delegations_tenant_id_idx").on(table.tenantId)]
);

export const electronicSignatures = pgTable(
  "electronic_signatures",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    tenantId: text("tenant_id").notNull(),
    userId: text("user_id").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: text("entity_id").notNull(),
    signatureType: signatureTypeEnum("signature_type").notNull(),
    meaning: signatureMeaningEnum("meaning").notNull(),
    reason: text("reason"),
    signedAt: timestamp("signed_at").defaultNow().notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    sessionId: text("session_id"),
  },
  (table) => [
    index("electronic_signatures_tenant_id_idx").on(table.tenantId),
  ]
);

// Relations
export const rolesRelations = relations(roles, ({ many }) => ({
  permissions: many(rolePermissions),
  assignments: many(userRoleAssignments),
}));

export const rolePermissionsRelations = relations(
  rolePermissions,
  ({ one }) => ({
    role: one(roles, {
      fields: [rolePermissions.roleId],
      references: [roles.id],
    }),
  })
);

export const userRoleAssignmentsRelations = relations(
  userRoleAssignments,
  ({ one }) => ({
    role: one(roles, {
      fields: [userRoleAssignments.roleId],
      references: [roles.id],
    }),
  })
);

export const departmentsRelations = relations(departments, ({ many }) => ({
  userAssignments: many(userDepartmentAssignments),
}));

export const userDepartmentAssignmentsRelations = relations(
  userDepartmentAssignments,
  ({ one }) => ({
    department: one(departments, {
      fields: [userDepartmentAssignments.departmentId],
      references: [departments.id],
    }),
  })
);

export const delegationsRelations = relations(delegations, ({ one }) => ({
  delegator: one(departments, {
    fields: [delegations.delegatorId],
    references: [departments.id],
  }),
}));
