// Generated by AI. Requires qualified professional review.
import {
  pgTable,
  pgEnum,
  text,
  timestamp,
  boolean,
  jsonb,
  index,
  unique,
} from "drizzle-orm/pg-core";
import { users } from "./users";

// ============================================================================
// ENUMS
// ============================================================================

export const compensationType = pgEnum("compensation_type", [
  "salary",
  "hourly",
]);

export const leaveType = pgEnum("leave_type", [
  "vacation",
  "sick",
  "personal",
  "fmla",
  "bereavement",
  "jury_duty",
  "military",
  "unpaid",
  "other",
]);

export const leaveRequestStatus = pgEnum("leave_request_status", [
  "pending",
  "approved",
  "denied",
  "cancelled",
]);

export const trainingStatus = pgEnum("training_status", [
  "assigned",
  "in_progress",
  "completed",
  "overdue",
  "waived",
]);

export const reviewStatus = pgEnum("review_status", [
  "draft",
  "self_assessment",
  "manager_review",
  "calibration",
  "approved",
  "acknowledged",
  "archived",
]);

export const ratingScale = pgEnum("rating_scale", [
  "1_needs_improvement",
  "2_developing",
  "3_meets_expectations",
  "4_exceeds_expectations",
  "5_outstanding",
]);

// ============================================================================
// COMPENSATION — Access restricted to hr_admin only
// ============================================================================

export const compensation = pgTable(
  "compensation",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    tenantId: text("tenant_id").notNull(),
    userId: text("user_id").notNull(),
    type: compensationType("type").notNull(),
    amount: text("amount").notNull(), // Stored as text to avoid floating point issues
    currency: text("currency").default("USD").notNull(),
    payGrade: text("pay_grade"),
    payBand: text("pay_band"),
    bonusEligible: boolean("bonus_eligible").default(false).notNull(),
    bonusTargetPercent: text("bonus_target_percent"),
    effectiveStart: timestamp("effective_start").notNull(),
    effectiveEnd: timestamp("effective_end"),
    reason: text("reason"),
    approvedBy: text("approved_by"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("compensation_tenant_user_idx").on(table.tenantId, table.userId),
  ]
);

// ============================================================================
// LEAVE BALANCES
// ============================================================================

export const leaveBalances = pgTable(
  "leave_balances",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    tenantId: text("tenant_id").notNull(),
    userId: text("user_id").notNull(),
    leaveType: leaveType("leave_type").notNull(),
    totalHours: text("total_hours").notNull(),
    usedHours: text("used_hours").default("0").notNull(),
    pendingHours: text("pending_hours").default("0").notNull(),
    year: text("year").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("leave_balances_tenant_user_idx").on(table.tenantId, table.userId),
    unique("leave_balances_unique").on(table.tenantId, table.userId, table.leaveType, table.year),
  ]
);

// ============================================================================
// LEAVE REQUESTS — fmlaDetails is NEVER returned to non-hr_admin users
// ============================================================================

export const leaveRequests = pgTable(
  "leave_requests",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    tenantId: text("tenant_id").notNull(),
    userId: text("user_id").notNull(),
    leaveType: leaveType("leave_type").notNull(),
    startDate: timestamp("start_date").notNull(),
    endDate: timestamp("end_date").notNull(),
    totalHours: text("total_hours").notNull(),
    reason: text("reason"),
    fmlaDetails: text("fmla_details"), // PRIVATE — only visible to HR Admin, NEVER to manager
    status: leaveRequestStatus("status").default("pending").notNull(),
    reviewedBy: text("reviewed_by"),
    reviewedAt: timestamp("reviewed_at"),
    reviewNotes: text("review_notes"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("leave_requests_tenant_user_idx").on(table.tenantId, table.userId),
    index("leave_requests_tenant_status_idx").on(table.tenantId, table.status),
  ]
);

// ============================================================================
// TRAINING ASSIGNMENTS
// ============================================================================

export const trainingAssignments = pgTable(
  "training_assignments",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    tenantId: text("tenant_id").notNull(),
    userId: text("user_id").notNull(),
    trainingName: text("training_name").notNull(),
    trainingCategory: text("training_category"),
    requiredForRole: text("required_for_role"),
    requiredForModule: text("required_for_module"),
    status: trainingStatus("status").default("assigned").notNull(),
    assignedDate: timestamp("assigned_date").defaultNow().notNull(),
    dueDate: timestamp("due_date"),
    completedDate: timestamp("completed_date"),
    completedBy: text("completed_by"),
    score: text("score"),
    certificateNumber: text("certificate_number"),
    expirationDate: timestamp("expiration_date"),
    assignedBy: text("assigned_by").notNull(),
    notes: text("notes"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("training_tenant_user_idx").on(table.tenantId, table.userId),
    index("training_tenant_status_idx").on(table.tenantId, table.status),
    index("training_tenant_expiry_idx").on(table.tenantId, table.expirationDate),
  ]
);

// ============================================================================
// PERFORMANCE REVIEWS
// ============================================================================

export const performanceReviews = pgTable(
  "performance_reviews",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    tenantId: text("tenant_id").notNull(),
    userId: text("user_id").notNull(),
    reviewerId: text("reviewer_id").notNull(),
    reviewCycle: text("review_cycle").notNull(),
    periodStart: timestamp("period_start").notNull(),
    periodEnd: timestamp("period_end").notNull(),
    status: reviewStatus("status").default("draft").notNull(),
    selfAssessment: text("self_assessment"),
    managerAssessment: text("manager_assessment"),
    overallRating: ratingScale("overall_rating"),
    goals: jsonb("goals"),
    strengths: text("strengths"),
    developmentAreas: text("development_areas"),
    approvedBy: text("approved_by"),
    approvedAt: timestamp("approved_at"),
    employeeAcknowledgedAt: timestamp("employee_acknowledged_at"),
    signatureId: text("signature_id"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("perf_reviews_tenant_user_idx").on(table.tenantId, table.userId),
    index("perf_reviews_tenant_reviewer_idx").on(table.tenantId, table.reviewerId),
    index("perf_reviews_tenant_status_idx").on(table.tenantId, table.status),
  ]
);
