// Generated by AI. Requires qualified professional review.
import {
  pgTable,
  pgEnum,
  text,
  timestamp,
  boolean,
  index,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { tenants } from "./tenants";

export const userRoleEnum = pgEnum("user_role", [
  "admin",
  "quality_manager",
  "regulatory_manager",
  "department_head",
  "engineer",
  "specialist",
  "viewer",
]);

export const employmentTypeEnum = pgEnum("employment_type", [
  "full_time",
  "part_time",
  "contractor",
  "temp",
  "intern",
]);

export const users = pgTable(
  "users",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    tenantId: text("tenant_id").notNull(),
    clerkUserId: text("clerk_user_id").notNull().unique(),
    email: text("email").notNull().unique(),
    name: text("name").notNull(), // Kept for backward compat — populated as firstName + " " + lastName
    firstName: text("first_name"),
    lastName: text("last_name"),
    middleName: text("middle_name"),
    username: text("username").unique(),
    title: text("title"),
    role: userRoleEnum("role").notNull(),
    department: text("department"),
    avatar: text("avatar"),
    isActive: boolean("is_active").default(true).notNull(),
    employmentType: employmentTypeEnum("employment_type").default("full_time").notNull(),
    managerId: text("manager_id"), // Self-referencing — references users.id
    location: text("location"),
    hireDate: timestamp("hire_date"),
    terminationDate: timestamp("termination_date"),
    terminationReason: text("termination_reason"),
    terminatedBy: text("terminated_by"),
    suspendedAt: timestamp("suspended_at"),
    suspendedReason: text("suspended_reason"),
    lastLogin: timestamp("last_login"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [index("users_tenant_id_idx").on(table.tenantId)]
);

export const usersRelations = relations(users, ({ one }) => ({
  tenant: one(tenants, {
    fields: [users.tenantId],
    references: [tenants.id],
  }),
}));
