// Generated by AI. Requires qualified professional review.
import { NextResponse } from "next/server";

const mockReviewCycles = [
  { id: "cycle-001", name: "2026 Annual", status: "active", startDate: "2026-01-01", endDate: "2026-12-31", reviewDeadline: "2026-03-31", createdAt: "2025-12-15" },
  { id: "cycle-002", name: "2025 Annual", status: "closed", startDate: "2025-01-01", endDate: "2025-12-31", reviewDeadline: "2025-03-31", createdAt: "2024-12-15", closedAt: "2025-04-15" },
];

export async function GET() {
  return NextResponse.json({ data: mockReviewCycles, total: mockReviewCycles.length });
}

export async function POST() {
  return NextResponse.json({ success: true, message: "Review cycle created" });
}
