// Generated by AI. Requires qualified professional review.
import { NextResponse } from "next/server";

const mockHistory = [
  {
    id: "AUD-101",
    action: "USER_UPDATED",
    field: "role",
    oldValue: "Document Controller",
    newValue: "Quality Manager",
    performedBy: "Aisha Patel",
    timestamp: "2026-03-20T11:00:00Z",
  },
  {
    id: "AUD-102",
    action: "ROLE_ASSIGNED",
    field: "role",
    oldValue: null,
    newValue: "Document Controller",
    performedBy: "Aisha Patel",
    timestamp: "2025-11-05T09:30:00Z",
  },
  {
    id: "AUD-103",
    action: "TRAINING_COMPLETED",
    field: "trainingStatus",
    oldValue: "overdue",
    newValue: "current",
    performedBy: "System",
    timestamp: "2025-09-12T14:15:00Z",
  },
  {
    id: "AUD-104",
    action: "DEPARTMENT_CHANGED",
    field: "department",
    oldValue: "Engineering",
    newValue: "Quality Assurance",
    performedBy: "Aisha Patel",
    timestamp: "2025-06-01T08:00:00Z",
  },
  {
    id: "AUD-105",
    action: "USER_CREATED",
    field: null,
    oldValue: null,
    newValue: null,
    performedBy: "System",
    timestamp: "2024-06-15T09:00:00Z",
  },
];

export async function GET(
  _request: Request,
  { params }: { params: { id: string } }
) {
  void params;
  return NextResponse.json({ history: mockHistory, total: mockHistory.length });
}
