// Generated by AI. Requires qualified professional review.
import { NextResponse } from "next/server";
// import { logAuditEvent } from "@/server/services/audit-log";

const mockUsers = [
  {
    id: "USR-001",
    name: "Dr. Sarah Chen",
    email: "sarah.chen@meddevice.com",
    department: "Quality Assurance",
    role: "Quality Manager",
    status: "active",
    lastLogin: "2026-04-01T14:32:00Z",
  },
  {
    id: "USR-002",
    name: "James Rodriguez",
    email: "james.rodriguez@meddevice.com",
    department: "Regulatory Affairs",
    role: "Regulatory Specialist",
    status: "active",
    lastLogin: "2026-04-01T09:15:00Z",
  },
  {
    id: "USR-003",
    name: "Emily Watson",
    email: "emily.watson@meddevice.com",
    department: "Engineering",
    role: "Design Engineer",
    status: "active",
    lastLogin: "2026-03-31T16:45:00Z",
  },
  {
    id: "USR-004",
    name: "Michael Okafor",
    email: "michael.okafor@meddevice.com",
    department: "Manufacturing",
    role: "Production Supervisor",
    status: "active",
    lastLogin: "2026-04-02T08:00:00Z",
  },
  {
    id: "USR-005",
    name: "Lisa Park",
    email: "lisa.park@meddevice.com",
    department: "Quality Assurance",
    role: "Document Controller",
    status: "active",
    lastLogin: "2026-03-30T11:20:00Z",
  },
  {
    id: "USR-006",
    name: "Robert Müller",
    email: "robert.muller@meddevice.com",
    department: "Clinical Affairs",
    role: "Clinical Specialist",
    status: "inactive",
    lastLogin: "2026-02-15T10:00:00Z",
  },
  {
    id: "USR-007",
    name: "Aisha Patel",
    email: "aisha.patel@meddevice.com",
    department: "Regulatory Affairs",
    role: "Admin",
    status: "active",
    lastLogin: "2026-04-02T07:30:00Z",
  },
  {
    id: "USR-008",
    name: "David Thornton",
    email: "david.thornton@meddevice.com",
    department: "Engineering",
    role: "Supplier Quality Engineer",
    status: "active",
    lastLogin: "2026-03-28T13:55:00Z",
  },
];

export async function GET() {
  return NextResponse.json({ users: mockUsers, total: mockUsers.length });
}

export async function POST(request: Request) {
  const body = await request.json();
  // await logAuditEvent({ action: "USER_CREATED", details: body });
  void body;
  return NextResponse.json(
    { success: true, message: "User created" },
    { status: 201 }
  );
}
