// Generated by AI. Requires qualified professional review.
import { NextResponse } from "next/server";
// import { logAuditEvent } from "@/server/services/audit-log";

export async function DELETE(
  _request: Request,
  { params }: { params: { id: string } }
) {
  // await logAuditEvent({ action: "ASSIGNMENT_REVOKED", assignmentId: params.id });
  void params;
  return NextResponse.json({ success: true, message: "Assignment revoked" });
}
