// Generated by AI. Requires qualified professional review.
import { NextResponse } from "next/server";

const mockLeaveBalances = [
  { employeeId: "emp-001", name: "Alice Johnson", vacation: { total: 160, used: 48 }, sick: { total: 80, used: 8 }, personal: { total: 24, used: 8 } },
  { employeeId: "emp-002", name: "Bob Smith", vacation: { total: 120, used: 80 }, sick: { total: 80, used: 16 }, personal: { total: 24, used: 16 } },
  { employeeId: "emp-003", name: "Carol Davis", vacation: { total: 200, used: 40 }, sick: { total: 80, used: 0 }, personal: { total: 24, used: 0 } },
  { employeeId: "emp-004", name: "Dan Wilson", vacation: { total: 120, used: 120 }, sick: { total: 80, used: 24 }, personal: { total: 24, used: 24 } },
  { employeeId: "emp-005", name: "Eva Martinez", vacation: { total: 160, used: 64 }, sick: { total: 80, used: 8 }, personal: { total: 24, used: 8 } },
  { employeeId: "emp-006", name: "Frank Lee", vacation: { total: 80, used: 16 }, sick: { total: 80, used: 40 }, personal: { total: 24, used: 0 } },
  { employeeId: "emp-007", name: "Grace Chen", vacation: { total: 200, used: 96 }, sick: { total: 80, used: 0 }, personal: { total: 24, used: 16 } },
  { employeeId: "emp-008", name: "Hank Brown", vacation: { total: 120, used: 32 }, sick: { total: 80, used: 8 }, personal: { total: 24, used: 8 } },
];

export async function GET() {
  return NextResponse.json({ data: mockLeaveBalances, total: mockLeaveBalances.length });
}
