// Generated by AI. Requires qualified professional review.
import { NextResponse } from "next/server";
// import { logAuditEvent } from "@/server/services/audit-log";

export async function POST(
  _request: Request,
  { params }: { params: { id: string } }
) {
  // await logAuditEvent({ action: "USER_DEACTIVATED", userId: params.id });
  void params;
  return NextResponse.json({ success: true, message: "User deactivated" });
}
