// Generated by AI. Requires qualified professional review.
import { NextResponse } from "next/server";
// import { logAuditEvent } from "@/server/services/audit-log";

const mockRoles = [
  {
    id: "ROLE-001",
    name: "Admin",
    type: "system",
    description: "Full system access with user and configuration management",
    userCount: 2,
    isActive: true,
  },
  {
    id: "ROLE-002",
    name: "Quality Manager",
    type: "system",
    description: "Manages quality processes, CAPAs, and document approvals",
    userCount: 3,
    isActive: true,
  },
  {
    id: "ROLE-003",
    name: "Regulatory Specialist",
    type: "system",
    description: "Handles regulatory submissions and compliance monitoring",
    userCount: 4,
    isActive: true,
  },
  {
    id: "ROLE-004",
    name: "Document Controller",
    type: "system",
    description: "Controls document lifecycle including review and release",
    userCount: 2,
    isActive: true,
  },
  {
    id: "ROLE-005",
    name: "Design Engineer",
    type: "system",
    description: "Creates and maintains design history files and risk analyses",
    userCount: 6,
    isActive: true,
  },
  {
    id: "ROLE-006",
    name: "Auditor",
    type: "system",
    description: "Read-only access for internal and external audit activities",
    userCount: 3,
    isActive: true,
  },
  {
    id: "ROLE-007",
    name: "Viewer",
    type: "system",
    description: "Read-only access to released documents and records",
    userCount: 12,
    isActive: true,
  },
  {
    id: "ROLE-008",
    name: "Supplier Quality Engineer",
    type: "custom",
    description: "Manages supplier qualifications and incoming inspections",
    userCount: 2,
    isActive: true,
  },
  {
    id: "ROLE-009",
    name: "Clinical Specialist",
    type: "custom",
    description: "Manages clinical evaluation reports and post-market surveillance",
    userCount: 1,
    isActive: false,
  },
];

export async function GET() {
  return NextResponse.json({ roles: mockRoles, total: mockRoles.length });
}

export async function POST(request: Request) {
  const body = await request.json();
  // await logAuditEvent({ action: "ROLE_CREATED", details: body });
  void body;
  return NextResponse.json(
    { success: true, message: "Role created" },
    { status: 201 }
  );
}
